### PR TITLE
fix(discovery): check for db cached folder quota during discovery for some items.

### LINKED ISSUE #8278: Store quota of folders in db
Currently the quota is not being correctly checked if a PROPFIND request was not done.
The client needs to cache the information and the server needs to notify the client of changes: https://github.com/nextcloud/server/issues/52875

- to do:
  - [ ] server side work: https://github.com/nextcloud/server/issues/52875
  - [x] do not use the check in discovery if the the remote entry is not valid (no PROPFIND request was done) -> @mgallien fixed it with https://github.com/nextcloud/desktop/pull/8279
  - [x] store quota values in the the db when a PROPFIND is done -> @camilasan  

@Rello ^^

### PR DESCRIPTION
**Pull request by camilasan**
Fix #8278.

### CODE REVIEW

File: src/libsync/syncfileitem.cpp [hunk 1]
```diff
@@ -238,6 +242,11 @@ SyncFileItemPtr SyncFileItem::fromProperties(const QString &filePath, const QMap
         item->_livePhotoFile = properties.value(QStringLiteral("metadata-files-live-photo"));
     }
 
+    if (isDirectory && properties.contains(QStringLiteral("quota-used-bytes")) && properties.contains(QStringLiteral("quota-available-bytes"))) {
+        item->_folderQuota.bytesUsed = properties.value(QStringLiteral("quota-used-byte")).toLongLong();
```
Comment (nilsding) [inline src/libsync/syncfileitem.cpp]: typo:

```suggestion
        item->_folderQuota.bytesUsed = properties.value(QStringLiteral("quota-used-bytes")).toLongLong();
```

might be a good idea to make these names available as a constant

File: test/syncenginetestutils.cpp [hunk 2]
```diff
@@ -128,12 +128,6 @@ void DiskFileModifier::setE2EE([[maybe_unused]] const QString &relativePath, [[m
 {
 }
 
-QFile DiskFileModifier::find(const QString &relativePath) const
-{
-    const auto path = _rootDir.filePath(relativePath);
-    return QFile(path);
-}
```
Comment (nilsding) [inline test/syncenginetestutils.cpp]: why did this get removed?

(fwiw that's fine by me as long as the other tests don't depend on that specific method)

File: test/testlocaldiscovery.cpp [hunk 3]
```diff
@@ -866,6 +866,113 @@ private slots:
...
+        // create local fileNameC - size < quota in db
+        const QString fileNameC("A/C.data");
+        fakeFolder.localModifier().insert(fileNameC, 0);
+
+        // sync filenameC - size < quota in db => success
+        syncSpy.clear();
+        QVERIFY(fakeFolder.syncOnce());
+        QCOMPARE(syncSpy.findItem(fileNameC)->_status, SyncFileItem::Status::Success);
+
+        // check db quota for folderA - bytesAvailable have changed to 0 due to new PROPFIND
```
Comment (mgallien) [inline test/testlocaldiscovery.cpp]:
```suggestion
        // check db quota for folderA - bytesAvailable have changed to 600 due to new PROPFIND
```

File: test/syncenginetestutils.h [hunk 4]
```diff
@@ -150,6 +153,7 @@ class FileInfo : public FileModifier
     void modifyLockState(const QString &relativePath, LockState lockState, int lockType, const QString &lockOwner, const QString &lockOwnerId, const QString &lockEditorId, quint64 lockTime, quint64 lockTimeout) override;
 
     void setE2EE(const QString &relativepath, const bool enabled) override;
+    void setFolderQuota(const QString &relativePath, const FolderQuota newQuota);
```
Comment (mgallien) [inline test/syncenginetestutils.h]: similarly to the `find`method, can you add a specific parameter to indicate that etag is going to be modified or not modified ?
for example: `const bool invalidateEtags = false` (or even better with an enum that avoids the `bool` API hell)

File: src/libsync/discovery.h [hunk 5]
```diff
@@ -298,7 +299,7 @@ class ProcessDirectoryJob : public QObject
 
     FolderQuota _folderQuota;
 
-    int64_t folderQuotaAvailable(const SyncFileItemPtr &item);
+    int64_t folderBytesAvailable(const SyncFileItemPtr &item, const bool isServerEntryValid);
```
Comment (mgallien) [inline src/libsync/discovery.h]: replace `bool` by an enum type to have a better API (way more readable than `false` or `true`)

File: src/libsync/discovery.cpp [hunk 6]
```diff
@@ -1178,16 +1167,19 @@ void ProcessDirectoryJob::processFileAnalyzeLocalInfo(
...
-                             << "item used:" << item->_folderQuota.bytesUsed
-                             << "item available:" << item->_folderQuota.bytesAvailable
-                             << "- quota used: " << serverEntry.folderQuota.bytesUsed
-                             << "- quota available: " << serverEntry.folderQuota.bytesAvailable;
+        const auto isServerEntryValid = serverEntry.isValid();
+        if (const auto folderQuota = folderBytesAvailable(item, isServerEntryValid);
+            item->_size > folderQuota
+            && folderQuota > -1) {
+
+            qCDebug(lcDisco) << "Quota exceeded for item:" << item->_file
```
Comment (mgallien) [inline src/libsync/discovery.cpp]: should we change the level ?
debug level means that it will be missing from production logs

**Review by mgallien — CHANGES_REQUESTED** [review]
see my inline comments

File: src/libsync/discovery.cpp (hunk 6 above)
Comment (camilasan) [reply src/libsync/discovery.cpp]: I thought we wanted to have less logs, that is why.

File: test/syncenginetestutils.h [hunk 7]
```diff
@@ -127,6 +127,15 @@ class FileInfo : public FileModifier
     FileInfo(const QString &name, qint64 size, char contentChar, QDateTime mtime) : name{name}, isDir{false}, lastModified(mtime), size{size}, contentChar{contentChar} { }
     FileInfo(const QString &name, const std::initializer_list<FileInfo> &children);
 
+    enum Etags {
+        Validate = 0,
```
Comment (mgallien) [inline test/syncenginetestutils.h]:
```suggestion
        KeepUnmodified = 0,
```
feel free to find a better name
it is either the value is invalidated or the previous value is kept

**Review by mgallien — CHANGES_REQUESTED** [review]

**Review by mgallien — APPROVED** [review]

**Review by nilsding — APPROVED** [review]
