### PR TITLE
Ask before importing accounts from legacy clients

### LINKED ISSUE #5556: [Bug]: Client uses ownCloud configuration on first start
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Freshly installed nextcloud when starting, complains about an incompatible server. Turns out this is a server which I use with my owncloud client and which is configured in .config/ownCloud/owncloud.cfg

I do not want this and I cannot find a way to prevent it. Even when I specify my own config directory using --confdir somedir, the same happens. 

### Steps to reproduce

run nextcloud client for the first time with some owncloud config present

### Expected behavior

Ignore the config which is not your concern, possibly providing the option to import it. 

At least provide a command line option NOT TO USE the owncloud config. 

### Which files are affected by this bug

none

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04.2 LTS

### Package

Appimage

### Nextcloud Server version

does not matter

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
Displays dialog asking user to confirm if they'd like to attempt an import of legacy accounts.

Also adds a command line argument to force imports if needed

Closes #5556

### CODE REVIEW

File: src/gui/application.cpp [hunk 1]
```diff
@@ -95,7 +95,8 @@ namespace {
         "  --localdirpath       : (optional) path where to create a local sync folder when creating an account via command-line.\n"
         "  --isvfsenabled       : whether to set a VFS or non-VFS folder (1 for 'yes' or 0 for 'no') when creating an account via command-line.\n"
         "  --remotedirpath      : (optional) path to a remote subfolder when creating an account via command-line.\n"
-        "  --serverurl          : a server URL to use when creating an account via command-line.\n";
+        "  --serverurl          : a server URL to use when creating an account via command-line.\n"
+        "  --forcelegacyimport  : forcefully import account configurations from legacy clients (if available).\n";
```
Comment (allexzander) [inline src/gui/application.cpp:99]: @claucambra I would be more specific with argument names as it confuses me of what legacy import is this related to. Would be easier to read if the name was something like `--forcelegacyconfigimport`

**Review by allexzander — CHANGES_REQUESTED** [review]

File: src/gui/accountmanager.cpp [hunk 2]
```diff
@@ -531,4 +544,19 @@ void AccountManager::addAccountState(AccountState *accountState)
     _accounts << ptr;
     emit accountAdded(accountState);
 }
+
+bool AccountManager::forceLegacyImport() const
```
Comment (allexzander) [inline src/gui/accountmanager.cpp:548]: @claucambra I do not see where this is used. Shouldn't you skip the popup if this is set?

**Review by allexzander — CHANGES_REQUESTED** [review]

File: src/gui/application.cpp (hunk 1 above)
Comment (claucambra) [reply src/gui/application.cpp]: Okay, changed

File: src/gui/accountmanager.cpp (hunk 2 above)
Comment (claucambra) [reply src/gui/accountmanager.cpp:557]: Oops, didn't push the commit -- the dialog is now skipped if this is true
