### PR TITLE
fix(network): fall back to unlimited bandwidth in case the legacy global limit is still set

### LINKED ISSUE #8743: [Bug]: "Automated Bandwidth" network settings  leading to slow sync
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Since 3.17 upgrade, the sync is extremely slow.

### Steps to reproduce

1. Upgrade from 3.16.6 to 3.17
2. Sync a folder

### Expected behavior

No sync regression

### Which files are affected by this bug

all files, even small ones

### Operating system

Linux

### Which version of the operating system you are running.

Arch

### Package

Distro package manager

### Nextcloud Server version

31.0.9

### Nextcloud Desktop Client version

3.17.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.16.3 to 3.17.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [x] Other

### Nextcloud Server logs

```shell
none
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nilsding**
`-2` used to mean "Use global limits", which no longer exist since 3.17.0.  As any negative value results in the auto bandwidth limiter to engage, this could result in unexpected slower sync speeds after a client upgrade.

Let's just keep handling that value and assume that we want to use unlimited bandwidth.

Fixes #8743

### CODE REVIEW

File: src/libsync/account.cpp [hunk 1]
```diff
@@ -1437,8 +1444,15 @@ void Account::setDownloadLimitSetting(const AccountNetworkTransferLimitSetting s
     if (setting == _downloadLimitSetting) {
         return;
     }
-    
-    _downloadLimitSetting = setting;
+
+    auto targetSetting = setting;
+
+    if (setting == AccountNetworkTransferLimitSetting::LegacyGlobalLimit) {
+        qCWarning(lcAccount) << "Download limit setting was requested to be set to the legacy global limit, falling back to unlimited";
```
Comment (camilasan) [inline src/libsync/account.cpp]: maybe change to qCInfo?

File: src/libsync/account.cpp [hunk 2]
```diff
@@ -1423,7 +1423,14 @@ void Account::setUploadLimitSetting(const AccountNetworkTransferLimitSetting set
         return;
     }
 
-    _uploadLimitSetting = setting;
+    auto targetSetting = setting;
+
+    if (setting == AccountNetworkTransferLimitSetting::LegacyGlobalLimit) {
+        qCWarning(lcAccount) << "Upload limit setting was requested to be set to the legacy global limit, falling back to unlimited";
```
Comment (camilasan) [inline src/libsync/account.cpp]: I would also switch to qCInfo or even qCDebug.

Comment (nilsding) [reply src/libsync/account.cpp]: will change them to qCInfo; these messages are printed only one time when the client starts.

Once the account config is saved, the config file contains the correct value
