### PR TITLE
gui/macOS: Improve/fix illegal File Provider domain handling for macOS VFS

### LINKED ISSUE #7694: [Bug]: cannot open the nextcloud directory on my mac when using .app domain.
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I Have cola16.app domain.
Image
when I access the directory, I got this error.
Image

I can access the directory.
Image

the directory name is ended with .app, so macos recognize the directory as application bundle.

can I change the Directory name?

### Steps to reproduce

sync with .app domain
Synchronize with nextcloud on the .app domain.

### Expected behavior

Expect: Open directory.
real: launch app.

### Which files are affected by this bug

nextcloud-vfs for mac

### Operating system

macOS

### Which version of the operating system you are running.

macOS 15.2

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

29.0.10

### Nextcloud Desktop Client version

3.15.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

mac client log
[nextcloud-desktop-log.zip](https://github.com/user-attachments/files/18236089/nextcloud-desktop-log.zip)

### PR DESCRIPTION
**Pull request by claucambra**
- Avoid accidentally turning File Provider domain locations into bundles (Closes #7694)
- Fix conversion of sanitised domain identifiers into account identifiers

### CODE REVIEW

File: src/gui/macOS/fileproviderdomainmanager_mac.mm [hunk 1]
```diff
@@ -29,41 +31,98 @@
...
+
+    domainId.replace(illegalChars, "-");
+
+    // Some url domains like .app cause issues on macOS as these are also bundle extensions.
+    // Under the hood, fileproviderd will create a folder for the user to access the files named
+    // after the domain identifier. If the url domain is the same as a bundle extension, Finder
+    // will interpret this folder as a bundle and will not allow the user to access the files.
+    // Here we wrap the dot in the url domain extension to prevent this from happening.
+    for (const auto &ext : bundleExtensions) {
+        if (domainId.endsWith(ext)) {
```
Comment (nilsding) [inline src/gui/macOS/fileproviderdomainmanager_mac.mm:74]: this will work only as long as there is no port other than 80 or 443 specified, as `userIdAtHostWithPort` also contains the port in such a case

Comment (claucambra) [reply src/gui/macOS/fileproviderdomainmanager_mac.mm:74]: Argh, you are right. I will rethink this

Comment (claucambra) [reply src/gui/macOS/fileproviderdomainmanager_mac.mm:74]: Actually, that's ok -- that won't cause an issue with Finder

We have issues when the folder name ends in `.app`, for instance, but if there is a port specified that means the folder name won't end in a bundle extension

Comment (nilsding) [reply src/gui/macOS/fileproviderdomainmanager_mac.mm:74]: ah, true :)  all good then

**Review by nilsding — APPROVED** [review]
