### PR TITLE
Do not modify discovered files on disk if not necessary

### LINKED ISSUE #5842: [Bug]: Desktop Client updates inode status timestamp
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

During synchronization scan, the inode status timestamp (`st_ctimespec`) is updated.
This behaviour confuses applications that currently have access to the file since they can "believe" that the file has changed, the owner has changed, etc. 
nextcloud-stat

### Steps to reproduce

Within a terminal:

1. `> touch foo`
2. `> stat foo`
3. _wait for the next scan_
4. `> stat foo`
5. Observation: the `st_ctimespec` timestamps differ.

### Expected behavior

The `st_ctimespec` timestamp should remain unchanged.

### Which files are affected by this bug

As far I examined: any

### Operating system

Mac OS

### Which version of the operating system you are running.

Ventura 13.4.1 (intel)

### Package

Appimage

### Nextcloud Server version

25.0.7 Enterprise

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
This prevents the file metadata changing when it doesn't have to, causing conflicts in certain user applications

Close #5842

### CODE REVIEW

**Review by allexzander — APPROVED** [review]

**Review by allexzander — CHANGES_REQUESTED** [review]
Too early for approval, @claucambra kindly check failing test, and do not forget to squash commits, then I can approve, thx

**Comment by claucambra** [comment]
> this is missing an update in automated tests to justify and explain the changes

Added a test now

File: test/syncenginetestutils.h [hunk 1]
```diff
@@ -529,7 +531,10 @@ class FakeFolder
     [[nodiscard]] OCC::SyncEngine &syncEngine() const { return *_syncEngine; }
     [[nodiscard]] OCC::SyncJournalDb &syncJournal() const { return *_journalDb; }
 
-    FileModifier &localModifier() { return _localModifier; }
+    DiskFileModifier &localModifier()
+    {
+        return _localModifier;
+    }
```
Comment (mgallien) [inline test/syncenginetestutils.h:537]: breaks style and compilation

**Review by mgallien — CHANGES_REQUESTED** [review]

File: test/syncenginetestutils.h (hunk 1 above)
Comment (claucambra) [reply test/syncenginetestutils.h]: Apologies, removed this change and fixed the test

**Review by allexzander — CHANGES_REQUESTED** [review]
@claucambra Kindly check why  SyncCfApiTest (Failed) is failing

**Review by allexzander — APPROVED** [review]
