### PR TITLE
Ask server to recalculate checksum(hash)

### LINKED ISSUE #3409: Add checksum recalculate request from the client side after corresponding server-side PR is merged and released
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

According to server-side PR https://github.com/nextcloud/server/pull/27378

### PR DESCRIPTION
**Pull request by allexzander**
As https://github.com/nextcloud/server/pull/27378 is already merged and is going to be released in NC24.

This will fix #3409

### CODE REVIEW

**Comment by szaimen** [comment]
> As [nextcloud/server#27378](https://github.com/nextcloud/server/pull/27378) is already merged and is going to be released in NC24.

No it is not. See https://github.com/nextcloud/server/pull/29510

File: src/libsync/networkjobs.h [hunk 1]
```diff
@@ -498,6 +498,24 @@ private slots:
     bool finished() override;
 };
 
+/**
+ * @brief A basic file manipulation job
+ * @ingroup libsync
+ */
+class OWNCLOUDSYNC_EXPORT SimpleFileManipulationNetworkJob : public AbstractNetworkJob
```
Comment (mgallien) [inline src/libsync/networkjobs.h:505]: I would go with `SimpleFileJob` or `CustomVerbFileJob` like we have `DeleteFileJob`
by the way could you refactor existing very similar code like this `DeleteFileJob` class to share common code ?

File: src/common/checksums.h [hunk 2]
```diff
@@ -161,9 +167,12 @@ class OCSYNC_EXPORT ValidateChecksumHeader : public QObject
      */
     void start(std::unique_ptr<QIODevice> device, const QByteArray &checksumHeader);
 
+    QByteArray calculatedChecksumType() const;
+    QByteArray calculatedChecksum() const;
+
 signals:
     void validated(const QByteArray &checksumType, const QByteArray &checksum);
-    void validationFailed(const QString &errMsg);
+    void validationFailed(const QString &errMsg, FailureReason reason);
```
Comment (mgallien) [inline src/common/checksums.h:175]: is there a reason not to also add `calculatedChecksumType` and `calculatedChecksum` to avoid doing a `qobject_cast` down the road ?

**Review by mgallien — COMMENTED** [review]
nice to have automated tests !
see my comments

File: src/common/checksums.h (hunk 2 above)
Comment (allexzander) [reply src/common/checksums.h:175]: @mgallien Isn't it more verbose to have additional arguments?

Comment (claucambra) [reply src/common/checksums.h:175]: Might be overkill but since we are overloading functions here a struct could be used to hold all of this data? Could be reused for the `validated` method too

Comment (mgallien) [reply src/common/checksums.h:175]: my point is that while `qobject_cast` might work, it is far from ideal to rely on it to be set while we could just add two extra args

Comment (allexzander) [reply src/common/checksums.h:175]: @mgallien That implies more changes, but, ok

**Comment by allexzander** [comment]
> > As [nextcloud/server#27378](https://github.com/nextcloud/server/pull/27378) is already merged and is going to be released in NC24.
> 
> No it is not yet. See [nextcloud/server#29510](https://github.com/nextcloud/server/pull/29510)

@szaimen Can I still assume this feature to be available in 24?

**Comment by szaimen** [comment]
> @szaimen Can I still assume this feature to be available in 24?

I don't know. Feel free to ask this in the files or engineering chat :)

**Comment by allexzander** [comment]
> nice to have automated tests ! see my comments

@mgallien Thank you. Fixed.

**Comment by allexzander** [comment]
@mgallien Any comments?

**Review by mgallien — APPROVED** [review]

**Review by claucambra — APPROVED** [review]

**Comment by allexzander** [comment]
this can wait till next major release
