### PR TITLE
Start file conflict resolve dialog asynchronous

### LINKED ISSUE #2804: Nextcloud version 3.1.1git crashes when solving conflicts files with style Fusion or Chameleon on ArchLinux
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Resolving conflicts should never crash Nextcloud.

### Actual behaviour
Here is the backtrace I got in [`gef` (an enhanced GDB)](https://gist.github.com/AkechiShiro/0d132831c9d3a3d55bdac22605bf7adf)

### Steps to reproduce
1. Have a lot of conflicts
2. Try to resolve them and then at some point
3. Notice the crash

### Client configuration
Client version: 
```
Nextcloud version 3.1.1git
Git revision 75c329f4ff3472774b00537e096ba8c987a6bb3c
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1i  8 Dec 2020'
Running on Arch Linux, x86_64
```

Operating system: ArchLinux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):
```
Using Qt 5.15.2, built against Qt 5.15.2
```

Client package (From Nextcloud or distro) (Linux only): coming from distro, the community repo of the ArchLinux official repo

Installation path of client:`/bin/nextcloud`

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: the log file is huge about 58MB I can't really upload it anywhere at the moment.

I will upload the client log file later when reproducing the bug again.

### PR DESCRIPTION
**Pull request by FlexW**
Fixes #2804

Signed-off-by: Felix Weilbach <felix.weilbach@t-online.de>

### CODE REVIEW

File: src/gui/tray/ActivityListModel.cpp [hunk 1]
```diff
@@ -444,13 +444,15 @@ void ActivityListModel::triggerDefaultAction(int activityIndex) const
...
+        auto dialog = new ConflictDialog;
+        dialog->setBaseFilename(baseName);
+        dialog->setLocalVersionFilename(conflictedPath);
+        dialog->setRemoteVersionFilename(basePath);
+        dialog->setAttribute(Qt::WA_DeleteOnClose);
+        connect(dialog, &ConflictDialog::accepted, [folder]() {
             folder->scheduleThisFolderSoon();
-        }
+        });
+        dialog->open();
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.cpp:455]: To be on the safe side I'd also force raising it and getting the focus. Since this dialog can't have a parent there's a slight chance it might "pop under" something else. You can use `ownCloudGui::raiseDialog()` for that.

File: src/gui/tray/ActivityListModel.cpp [hunk 2]
```diff
@@ -444,13 +445,19 @@ void ActivityListModel::triggerDefaultAction(int activityIndex) const
...
-            folder->scheduleThisFolderSoon();
+        if (!_currentConflictDialog.isNull()) {
+            _currentConflictDialog->close();
         }
+        _currentConflictDialog = new ConflictDialog;
+        _currentConflictDialog->setBaseFilename(baseName);
+        _currentConflictDialog->setLocalVersionFilename(conflictedPath);
+        _currentConflictDialog->setRemoteVersionFilename(basePath);
+        _currentConflictDialog->setAttribute(Qt::WA_DeleteOnClose);
+        connect(_currentConflictDialog, &ConflictDialog::accepted, [folder]() {
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.cpp:456]: For extra safety, `folder` should be passed as third parameter of that connect just before the lambda. In case the folder object would be deleted before accepted is emitted it would thus disconnect automatically, otherwise it won't and you risk calling into a deleted object from the lambda.

**Review by er-vin — APPROVED** [review]
