### PR TITLE
Bugfix/better handling of locked files during upload

### LINKED ISSUE #9111: [Bug]: Desktop client stops syncing if 1 or more files are locked
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

## Bug environment/pre-conditions

In my local sync folder, there is 1 .pst file which is opened (exclusively) by MS Outlook (classic).

When the desktop clients starts syncing, the PST file leads to an unexpected error (a message appears to restart sync, but the next sync still runs into the very same problem)

Image

Image

## Bug description

The bug itself is
* [ ] LOW PRIO: the lack of detection of the file as being locked which might lead to the following error
  * [ ] expected: no error, but information about a temporarily locked file in ignore list
* [ ] HIGH PRIO: when other files are in queue to be synced (from local client to server as well as from server to local client), these files are NOT synced UNTIL I close the MS Outlook application which closes the exlusive lock on the .pst file.

## Situation in OwnCloud Desktop client

OwnCloud correctly handles this issue with
1. detecting the file lock
2. showing the file in the ignore list with correct reason
3. continues syncing for other files

Image

### Steps to reproduce

1. Place a file (e.g. PST mailbox store) in a synced directory
2. Open the file (exclusively?!) with an application (e.g. MS Outlook classic for .pst files)
3. Change other files locally and/or server

### Expected behavior

Nextcloud desktop client should
1. correctly detect the file lock
2. show the file in sync log as temporary locked and with correct reason
3. continue syncing for other files 

### Which files are affected by this bug

*.pst

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

32.0.1

### Nextcloud Desktop Client version

4.0.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.16.1 to 3.16.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by mgallien**
close #9111

### CODE REVIEW

**Comment by mgallien** [comment]
possibly related https://github.com/nextcloud/desktop/issues/6131

File: src/libsync/propagateupload.cpp [hunk 1]
```diff
@@ -36,6 +36,7 @@
 namespace OCC {
 
 Q_LOGGING_CATEGORY(lcPutJob, "nextcloud.sync.networkjob.put", QtInfoMsg)
+Q_LOGGING_CATEGORY(lcUploadDevice, "nextcloud.sync.uploadevice", QtInfoMsg)
```
Comment (nilsding) [inline src/libsync/propagateupload.cpp]: typo:


```suggestion
Q_LOGGING_CATEGORY(lcUploadDevice, "nextcloud.sync.uploaddevice", QtInfoMsg)
```

**Review by nilsding — APPROVED** [review]

File: src/libsync/propagateupload.cpp (hunk 1 above)
Comment (mgallien) [reply src/libsync/propagateupload.cpp]: done
