### PR TITLE
fix(cloudprovider): add open main dialog action

### LINKED ISSUE #8645: [Bug]: Nextcloud GUI window invisible in Debian
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hi,

similar the issue addressed here:
https://github.com/nextcloud/desktop/pull/8217 and here:
https://github.com/nextcloud/desktop/issues/7135

The issue is that the gui window remains transparent. Sometimes this changes, when I restart it several times or when i start it from the terminal but not always. I am on debian sid and use the newest appimage from the website.
these are the logs when i start it from the terminal:

>  Failed to initialize instances shared memory:  "QSharedMemory::handle: doesn't exist"
> nextcloud.gui.application: Migrating old config from "/home/jayjag/.local/share/Nextcloud" to "/home/jayjag/.config/Nextcloud"
> nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/jayjag/.local/share/Nextcloud" to "/home/jayjag/.config/Nextcloud" )
> nextcloud.gui.application: Will move the individual files QList("Nextcloud_sync.log", "Nextcloud_sync.log.1")
> nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed
> nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log.1" also failed

Any ideas?
Cheers
Justus

### Steps to reproduce

double click on Nextcloud-3.17.1-x86_64.AppImage or in the terminal ./Nextcloud-3.17.1-x86_64.AppImage

### Expected behavior

it should open the GUI

### Which files are affected by this bug

Nextcloud-3.17.1-x86_64.AppImage

### Operating system

Linux

### Which version of the operating system you are running.

Debian sid

### Package

Official Linux AppImage

### Nextcloud Server version

Nextcloud AIO v11.6.0

### Nextcloud Desktop Client version

3.17.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

[__nextcloud_client_buildinfo.txt](https://github.com/user-attachments/files/21969262/__nextcloud_client_buildinfo.txt)
[__nextcloud_client_parameters.txt](https://github.com/user-attachments/files/21969261/__nextcloud_client_parameters.txt)

### PR DESCRIPTION
**Pull request by mgallien**
when opening the contextual menu of a cloud folder, add an entry to open the main dialog

also improve the text of the entry to open in the browser

Close #8645

### CODE REVIEW

**Comment by mgallien** [comment]
before

image

after

image

File: src/gui/cloudproviders/cloudproviderwrapper.cpp [hunk 1]
```diff
@@ -221,7 +221,14 @@ GMenuModel* CloudProviderWrapper::getMenuModel() {
     _mainMenu = g_menu_new();
 
     section = g_menu_new();
-    item = addMenuItem(tr("Open website"), "cloudprovider.openwebsite");
+    item = addMenuItem(tr("Open main dialog"), "cloudprovider.openmaindialog");
```
Comment (kra-mo) [inline src/gui/cloudproviders/cloudproviderwrapper.cpp]: "Main dialog" is quite technical and I had no idea what this would do before reading the issue.

Just "Open Nextcloud Desktop" would be better imo.

It should also probably be the last context menu item instead of the first as I don't think it would be used a lot (since it is not actually contextual to a file, same as eg. Help)

**Review by kra-mo — CHANGES_REQUESTED** [review]

File: src/gui/cloudproviders/cloudproviderwrapper.cpp (hunk 1 above)
Comment (nilsding) [reply src/gui/cloudproviders/cloudproviderwrapper.cpp]: The same text [appears in the tray icon context menu](https://github.com/user-attachments/assets/42ead78a-223e-4e2b-807a-2aa465cf03a2) (on Windows and some Linux desktops at least), so I guess we should we change that one as well then...

Comment (mgallien) [reply src/gui/cloudproviders/cloudproviderwrapper.cpp]: this menu is the one you get when clicking on the side bar to access your synchronization folders
image

if you are using Gnome without a system tray (may be the default), this might be the only way to open the client activity list window

I will push an extra commit to improve the text

Comment (mgallien) [reply src/gui/cloudproviders/cloudproviderwrapper.cpp]: I did change the action title as suggested

File: src/gui/systray.cpp [hunk 2]
```diff
@@ -176,7 +176,7 @@ void Systray::setupContextMenu()
     if (AccountManager::instance()->accounts().isEmpty()) {
         _contextMenu->addAction(tr("Add account"), this, &Systray::openAccountWizard);
     } else {
-        _contextMenu->addAction(tr("Open main dialog"), this, [this]{ showWindow(); });
+        _contextMenu->addAction(tr("Open Nextcloud Desktop"), this, [this]{ showWindow(); });
```
Comment (nilsding) [inline src/gui/systray.cpp]: for branding reasons these strings should set the app name through a parameter

```suggestion
        _contextMenu->addAction(tr("Open %1 Desktop").arg(Theme::instance()->appNameGUI()), this, [this]{ showWindow(); });
```

Comment (mgallien) [reply src/gui/systray.cpp]: thanks
very good catch

**Comment by mgallien** [comment]
@kra-mo any other ideas on what to improve in this PR
current state is
image
