### PR TITLE
Fix crash in cldapi.dll

### LINKED ISSUE #3349: Crash during sync due to CLDAPI.dll error
### Expected behaviour
Should sync the files.

### Actual behaviour
Crashes.

### Steps to reproduce
1. Start nextcloud
2. Press resume sync
3. Crash

### Client configuration
Client version: 3.2.1

Operating system: Windows 10 Build 19043

OS language: Turkish

Installation path of client: C:\Program Files\Nextcloud\nextcloud.exe

### Logs

In the debugger the error comes down to:

cldapi.dll;IssueHsmControl()

"Unhandled exception at 0x00007FF8BFD24B2A (cldapi.dll) in nextcloud.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFE."

### PR DESCRIPTION
**Pull request by mmdanggg2**
Fixes #3349

The problem was occurring because inside cldapi some of the functions (CfUpdatePlaceholder) internally call CfReferenceProtectedHandle and CfReleaseProtectedHandle which seems to make the memory the handle points to invalid sometimes, seems to depend on what kind of handle it gave in the first place. Then when we call again (CfSetPinState) with the same handle, due to the invalid memory there it ends up dereferencing it twice causing the crash. Seems like more of a bug in cldapi but there's not much we can do about that.

This solution is just to get a new handle each time we use it for a function. This at least prevents a hard crash as it was before, although as stated in the issue there seems to be quite a few other errors thrown up from my cldapi. Possibly related but it will sync if it retries enough.

Signed-off-by: James Horsley <jbhorsley@gmail.com>

### CODE REVIEW

File: src/libsync/vfs/cfapi/vfs_cfapi.cpp [hunk 1]
```diff
@@ -157,9 +157,9 @@ Result<void, QString> VfsCfApi::convertToPlaceholder(const QString &filename, co
 
     const auto handle = cfapi::handleForPath(localPath);
```
Comment (allexzander) [inline src/libsync/vfs/cfapi/vfs_cfapi.cpp:158]: @mmdanggg2 It looks like `cfapi::findPlaceholderInfo` is also asking to replace its argument type from `FileHandle` to `QString`. Now, we have to open a `handle` here just to check if placeholder info exists and then, we are not reusing that handle so it is just a redundant variable here. Also, it would be more consistent to always expect that `findPlaceholderInfo`, `updatePlaceholderInfo`, `convertToPlaceholder`, and `createPlaceholderInfo` all accept the same argument type.

Comment (mmdanggg2) [reply src/libsync/vfs/cfapi/vfs_cfapi.cpp]: I've changed over all the wrapper functions taking a handle to use QString path instead.

**Comment by mgallien** [comment]
> Fixes #3349
> 
> The problem was occurring because inside cldapi some of the functions (CfUpdatePlaceholder) internally call CfReferenceProtectedHandle and CfReleaseProtectedHandle which seems to make the memory the handle points to invalid sometimes, seems to depend on what kind of handle it gave in the first place. Then when we call again (CfSetPinState) with the same handle, due to the invalid memory there it ends up dereferencing it twice causing the crash. Seems like more of a bug in cldapi but there's not much we can do about that.
> 
> This solution is just to get a new handle each time we use it for a function. This at least prevents a hard crash as it was before, although as stated in the issue there seems to be quite a few other errors thrown up from my cldapi. Possibly related but it will sync if it retries enough.
> 
> Signed-off-by: James Horsley [jbhorsley@gmail.com](mailto:jbhorsley@gmail.com)



> Fixes #3349
> 
> The problem was occurring because inside cldapi some of the functions (CfUpdatePlaceholder) internally call CfReferenceProtectedHandle and CfReleaseProtectedHandle which seems to make the memory the handle points to invalid sometimes, seems to depend on what kind of handle it gave in the first place. Then when we call again (CfSetPinState) with the same handle, due to the invalid memory there it ends up dereferencing it twice causing the crash. Seems like more of a bug in cldapi but there's not much we can do about that.
> 
> This solution is just to get a new handle each time we use it for a function. This at least prevents a hard crash as it was before, although as stated in the issue there seems to be quite a few other errors thrown up from my cldapi. Possibly related but it will sync if it retries enough.
> 
> Signed-off-by: James Horsley [jbhorsley@gmail.com](mailto:jbhorsley@gmail.com)

Could you please try building with memory sanitizer activated (see https://github.com/nextcloud/desktop/pull/3171) ?
That would mean adding `-DECM_ENABLE_SANITIZERS=address`
Even if I know that CfApi can have problems, before we could merge your PR, we need to be really sure that is needed and what you se is not another problem.

**Comment by mmdanggg2** [comment]
Ok, I built master with the address sanitizer (Think I did it right) and it started spewing loads of access violations going through the clang_rt.asan_dynamic dll that are getting caught, is that normal? Made debugging in VS difficult though, just had to disable breaking on access violations and it ran until it hit the same unhandled exception in cldapi. Tried running it through windbg with sxi c0000005 to completely ignore access violations and it didn't print anything from after loading all the dlls up until it died hitting the exception in cldapi.

**Comment by mgallien** [comment]
> Ok, I built master with the address sanitizer (Think I did it right) and it started spewing loads of access violations going through the clang_rt.asan_dynamic dll that are getting caught, is that normal? Made debugging in VS difficult though, just had to disable breaking on access violations and it ran until it hit the same unhandled exception in cldapi. Tried running it through windbg with sxi c0000005 to completely ignore access violations and it didn't print anything from after loading all the dlls up until it died hitting the exception in cldapi.

Did you check that you are using the latest version of VS2019 ?
I am using 16.10.2 version (and updating to 16.10.3). If I remember correctly I used to have the same error when not doing a clean build. Might be a good idea to try that.

By the way, thanks for your work on that issue. I hope we can fix it for you in a way that make it working reliably (virtual files support).

**Comment by mmdanggg2** [comment]
Yep, just updated to 16.10.3 and did a clean build of the latest master with asan. VS didn't stop at every breakpoint this time, still spammed the debug output. Ran fine until hitting the cldapi exception with nothing I could see in the log.

```
...
Exception thrown at 0x00007FF8D0B93F77 (ntdll.dll) in nextcloud.exe: 0xE0736171: Access violation writing location 0x000004884694D000.
Exception thrown at 0x00007FF8D0B93F38 (ntdll.dll) in nextcloud.exe: 0xE0736171: Access violation writing location 0x000004884694E000.
Exception thrown at 0x00007FF8D0B93F77 (ntdll.dll) in nextcloud.exe: 0xE0736171: Access violation writing location 0x000004884694F000.
Exception thrown at 0x00007FF88A2859BA (cldapi.dll) in nextcloud.exe: 0xE0736171: Access violation reading location 0xFFFFFFFFFFFFFFFE.
Exception thrown at 0x00007FF8CE4C4ED9 (KernelBase.dll) in nextcloud.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFE.

The thread 0x52d0 has exited with code 0 (0x0).
Unhandled exception at 0x00007FF88A2859BA (cldapi.dll) in nextcloud.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFE.
```

I've been running it with my patch for the last 2 weeks and it does seem to be functioning fine. Definitely seems to me like there's some problem or incompatibility going on with cldapi itself. The standard client works fine on another machine with the same version of windows, connected to the same server with the same files so 🤷‍♂️.

**Comment by Erisa** [comment]
Just to share my experience and vouch for this PR:
I also have one machine (of many) affected by this problem (Which is amusing because making a VM on the same machine with the same Windows version has it work fine in there)

I used [nextcloud/client-building](https://github.com/nextcloud/client-building) to make a "Release" build of your fork soon after the last commit and have had it working perfectly fine ever since. The error went away and my tens of thousands of files are syncing fine. (I have server snapshots and backups in case it deleted them all)

File: src/libsync/vfs/cfapi/cfapiwrapper.h [hunk 2]
```diff
@@ -82,18 +82,18 @@ NEXTCLOUD_CFAPI_EXPORT bool isSparseFile(const QString &path);
 
 NEXTCLOUD_CFAPI_EXPORT FileHandle handleForPath(const QString &path);
 
-PlaceHolderInfo findPlaceholderInfo(const FileHandle &handle);
+PlaceHolderInfo findPlaceholderInfo(const QString & path);
```
Comment (allexzander) [inline src/libsync/vfs/cfapi/cfapiwrapper.h:85]: Please remove the space after `&`, so, `QString & path` becomes `QString &path`.

File: src/libsync/vfs/cfapi/cfapiwrapper.cpp [hunk 3]
```diff
@@ -606,14 +608,12 @@ OCC::CfApiWrapper::FileHandle OCC::CfApiWrapper::handleForPath(const QString &pa
     return {};
 }
 
-OCC::CfApiWrapper::PlaceHolderInfo OCC::CfApiWrapper::findPlaceholderInfo(const FileHandle &handle)
+OCC::CfApiWrapper::PlaceHolderInfo OCC::CfApiWrapper::findPlaceholderInfo(const QString & path)
```
Comment (allexzander) [inline src/libsync/vfs/cfapi/cfapiwrapper.cpp:611]: Please remove the space after `&`

File: src/libsync/vfs/cfapi/cfapiwrapper.h [hunk 4]
```diff
@@ -82,18 +82,18 @@ NEXTCLOUD_CFAPI_EXPORT bool isSparseFile(const QString &path);
...
 
 enum SetPinRecurseMode {
     NoRecurse = 0,
     Recurse,
     ChildrenOnly
 };
 
-NEXTCLOUD_CFAPI_EXPORT Result<OCC::Vfs::ConvertToPlaceholderResult, QString> setPinState(const FileHandle &handle, PinState state, SetPinRecurseMode mode);
+NEXTCLOUD_CFAPI_EXPORT Result<OCC::Vfs::ConvertToPlaceholderResult, QString> setPinState(const QString & path, PinState state, SetPinRecurseMode mode);
```
Comment (allexzander) [inline src/libsync/vfs/cfapi/cfapiwrapper.h:93]: Same `QString & path` -> `QString &path`

**Review by allexzander — CHANGES_REQUESTED** [review]

**Comment by allexzander** [comment]
@mmdanggg2 Just one change is needed and, please rebase interactively against the master, to squash all commits into one. I think this will be good to go.

**Comment by allexzander** [comment]
@FlexW @matthieugallien @camilasan any objections?

**Review by allexzander — APPROVED** [review]

**Comment by mgallien** [comment]
> @FlexW @matthieugallien @camilasan any objections?

yes, in current state I am not convinced

**Comment by mgallien** [comment]
> > @FlexW @matthieugallien @camilasan any objections?
> 
> yes, in current state I am not convinced

I mean, Kevin tried hard to use the proper CfApi way and we are moving away without a clear understanding about the root cause

**Comment by allexzander** [comment]
I am going to ask people who experience crash to test with your changes, then, I will get back here with the results.

**Comment by LucaOverflow** [comment]
I would like to test the changes but I didn't had the time to compile the Windows version yet.
Is it possible for you to create a Windows binary. I would think this wouldn't be a great effort for you.
Greetings Luca

**Comment by allexzander** [comment]
@LucaOverflow Please try this one https://cloud.nextcloud.com/s/9CiRxYQaFnXcwqK

**Comment by allexzander** [comment]
> > > @FlexW @matthieugallien @camilasan any objections?
> > 
> > 
> > yes, in current state I am not convinced
> 
> I mean, Kevin tried hard to use the proper CfApi way and we are moving away without a clear understanding about the root cause

@mgallien Yes, I understand Kevin's intent and fully support it. But, looks like there is indeed an internal issue in CfAPI, so, we have no choice but to adapt our code even though it may look not that posh eventually. We are having a crash and these changes somehow fix it for a few people https://github.com/nextcloud/desktop/issues/3349#issuecomment-891883079 I'd say we could try and find a good compromise and integrate it to fix a bunch of issues already opened. Kindly take another look when you have time.

**Comment by Erisa** [comment]
I second another look at this or something like this.

The current fixes available cause a different error "Couldn't update placeholder file" to break my usage of Nextcloud instead.
So Nextcloud is now unusable on Windows 11 for me, to the point where I stopped trying and uninstalled Nextcloud. Would love to have it back with a fix, just not familiar enough with C++ to try it myself

**Comment by mmdanggg2** [comment]
Got fed up with the 'Couldn't update placeholder info' errors and had another look at this. Always something stupid simple, the metadata struct wasn't being initialized so the FileAttributes field was just left to whatever random value that was on the stack at the time, causing the call to fail.

**Comment by Erisa** [comment]
@mmdanggg2 Is it possible for you to upload an (unsigned is fine unless nextcloud folks disallow it) build of this to test? I would build my own but I trashed the VM I was using recently and would have to setup another...

**Comment by mmdanggg2** [comment]
> 
> @mmdanggg2 Is it possible for you to upload an (unsigned is fine unless nextcloud folks disallow it) build of this to test? I would build my own but I trashed the VM I was using recently and would have to setup another...
Here's my build: https://www.mediafire.com/file/sr004my80stab2c/NextcloudCLDAPIFix.7z/file
Just be careful with it, I was having trouble with the #3978 PR syncing over and over and wiping out the date modified on everything so I didn't rebase up to that.

**Comment by Erisa** [comment]
Will be careful, thanks!

**Comment by himbolion** [comment]
> > @mmdanggg2 Is it possible for you to upload an (unsigned is fine unless nextcloud folks disallow it) build of this to test? I would build my own but I trashed the VM I was using recently and would have to setup another...
> 
> Here's my build: https://www.mediafire.com/file/sr004my80stab2c/NextcloudCLDAPIFix.7z/file Just be careful with it, I was having trouble with the #3978 PR syncing over and over and wiping out the date modified on everything so I didn't rebase up to that.

This build seems to fix Nextcloud for me. The Client was able to Sync with my Server without any problems / crashing

**Comment by Erisa** [comment]
This build is also working perfectly fine for me.
Over the time since first running it those 11 days ago, I have not had a single crash or problem, everything has worked perfectly. In contrast to the official builds which crash constantly and do not function.

**Comment by kamilko** [comment]
Can someone please put this request into next release? Because Nextcloud Desktop App is useless on WinSrv 2019. Just when nextcloud is begin to scan during the first sync, I have this error:

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> 
- <System> 
<Provider Name="Application Error" /> 
<EventID Qualifiers="0">1000</EventID> 
<Level>2</Level> 
<Task>100</Task> 
<Keywords>0x80000000000000</Keywords> 
<TimeCreated SystemTime="2021-12-01T18:52:25.973217400Z" /> 
<EventRecordID>35191</EventRecordID> 
<Channel>Application</Channel> 
<Computer>abetrdp.lxcloud.abet.dir</Computer> 
<Security /> 
</System> 
- <EventData> 
<Data>nextcloud.exe</Data> 
<Data>3.4.0.26041</Data> 
<Data>61a54ae0</Data> 
<Data>CLDAPI.dll</Data> 
<Data>10.0.17763.2237</Data> 
<Data>e14b4abe</Data> 
<Data>c0000005</Data> 
<Data>000000000001299a</Data> 
<Data>5d1c</Data> 
<Data>01d7e6e461025b53</Data> 
<Data>C:\Program Files\Nextcloud\nextcloud.exe</Data> 
<Data>C:\Windows\SYSTEM32\CLDAPI.dll</Data> 
<Data>d4815548-c1ee-441e-a422-6cdde244bc4f</Data> 
<Data /> 
<Data /> 
</EventData> 
</Event>
```

If user has empty folder it is OK, but whenever gets to around 80 files - crash is instant.
It also doesn't matter if I use regular user or Administrator account.

**Comment by mmdanggg2** [comment]
Update placeholder bug now fixed with #4012

**Comment by allexzander** [comment]
> Update placeholder bug now fixed with #4012

@mgallien ^^ FYI

**Comment by allexzander** [comment]
> Update placeholder bug now fixed with #4012

@mmdanggg2 But the crash is not fixed with #4012?

**Comment by mmdanggg2** [comment]
> > Update placeholder bug now fixed with #4012
> 
> @mmdanggg2 But the crash is not fixed with #4012?

@allexzander unfortunately it didn't seem like it. After I noticed that I did try a build with just the metadata fix but it was still crashing in the same spot. I had a quick look for other uninitialized values but didn't spot any.

**Comment by Jannos-443** [comment]
> > @mmdanggg2 Is it possible for you to upload an (unsigned is fine unless nextcloud folks disallow it) build of this to test? I would build my own but I trashed the VM I was using recently and would have to setup another...
> 
> Here's my build: https://www.mediafire.com/file/sr004my80stab2c/NextcloudCLDAPIFix.7z/file Just be careful with it, I was having trouble with the #3978 PR syncing over and over and wiping out the date modified on everything so I didn't rebase up to that.

fixed the Problem for me too.

**Comment by pwnorbitals** [comment]
Is this planned to be merged sometimes soon ? thanks

**Comment by vpsnotas** [comment]
> > > @mmdanggg2 Is it possible for you to upload an (unsigned is fine unless nextcloud folks disallow it) build of this to test? I would build my own but I trashed the VM I was using recently and would have to setup another...
> > 
> > 
> > Here's my build: https://www.mediafire.com/file/sr004my80stab2c/NextcloudCLDAPIFix.7z/file Just be careful with it, I was having trouble with the #3978 PR syncing over and over and wiping out the date modified on everything so I didn't rebase up to that.
> 
> fixed the Problem for me too.

It fixed my problem too, Thank you.

Problem on Windows Server 2019, nextcloud any version, including rc.

**Comment by limatus** [comment]
Hey Dev Team, is there any chance that we could merge this? I do have this problem now since circa one year, it's quite annoying TBH. All the best!

**Comment by mgallien** [comment]
we are actively working on this (the fix may end up be this PR or something else but we are careful not to break it for people unaffected by the crashes)

**Review by mgallien — APPROVED** [review]
