### PR TITLE
Make the share dialog resizeable

### LINKED ISSUE #4134: Increase size of share dialog
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### problem
Share dialog is too small for most information to fit in:

Screenshot_20220104_112817
Screenshot_20220104_112740
Screenshot_20220104_112718

### What should happen
Dialog should be... larger ;-)

It doesn't have to be huge, but why this tiny? making it twice as big would still be small compared to most dialogs on the desktop.

### Client configuration
Client version: 3.4.1 Linux

### LINKED ISSUE #4533: [Bug]: Design: Share window is too small for files with more than one recipient
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share window is too small to display all recipients in a human readable manner. 
When there are more than one recipient, you can scroll through them. But this looks really ugly an you do not get an good overview of the recipients because the window is so small. Only two recipients can get displayed at all. 
Problem gets worse with more recipients...

2022-05-13 14_34_04-Nextcloud-Freigabe

2022-05-13 14_35_03-Nextcloud-Freigabe

### Steps to reproduce

1. Right click on a file that was shared with more than one person
2. Click on Share Options
3. In the share window: Try to scroll through the recipients

### Expected behavior

Either, give the share window more height from the beginning. 
I would prefer this, because the window is really small and the buttons are too close to each other. 
Maybe give the window 30 % more height than width. This way it would kind of look like the side bar that every user knows from the browser. 

Or adjust the share windows' height dynamically with the amount of recipients. 

### Which files are affected by this bug

every shared file with more than 1 recipient

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

21.0.9

### Nextcloud Desktop Client version

3.5.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
https://user-images.githubusercontent.com/70155116/175035503-61904c6d-ee5b-4ece-b870-8aecdcc2d78a.mov

The default size of the dialog is now larger as well.

Closes #4134 and closes #4533

Signed-off-by: Claudio Cambra <claudio.cambra@gmail.com>

### CODE REVIEW

**Review by camilasan — APPROVED** [review]

File: src/gui/sharedialog.cpp [hunk 1]
```diff
@@ -35,6 +36,7 @@
 #include <QPointer>
 #include <QPushButton>
 #include <QFrame>
+#include <iostream>
```
Comment (mgallien) [inline src/gui/sharedialog.cpp:39]: are you sure you need it ?

Comment (claucambra) [reply src/gui/sharedialog.cpp]: Nope, sorry, was using for debugging. removed

**Review by mgallien — APPROVED** [review]
