### PR TITLE
fix: Handle server maintenance error in flow2auth

### LINKED ISSUE #9167: [Bug]: better handling of error when server needs an upgrade
- When setting up an account and the server needs an update, the client does not know how to handle the server response:

  Image

- After completing the update, the JSON error is still visible:

  Image

- To trigger the server state: putting the server in maintenance mode might do the trick.

### PR DESCRIPTION
**Pull request by Rello**
fixes #9167

### CODE REVIEW

**Comment by camilasan** [comment]
Screenshot 2025-12-11 at 10 44 10

File: src/gui/creds/flow2auth.cpp [hunk 1]
```diff
@@ -253,26 +253,40 @@ QJsonObject Flow2Auth::handleResponse(QNetworkReply *reply)
...
+
+        if (httpStatus == 503) {
+            errorReason = tr("The server is temporarily unavailable because it is in maintenance mode. "
+                             "Please try again once maintenance has finished.");
+        } else if (const auto errorFromJson = json["error"].toString();
             !errorFromJson.isEmpty()) {
-            errorReason = tr("Error returned from the server: <em>%1</em>")
+            errorReason = tr("An unexpected error occurred when trying to access the server. "
+                             "Please try to access it again later or contact your server administrator if the issue continues.")
             .arg(errorFromJson.toHtmlEscaped());
```
Comment (Aiiaiiio) [inline src/gui/creds/flow2auth.cpp]: I don't see a placeholder for this arg.

Comment (nilsding) [inline src/gui/creds/flow2auth.cpp]: since the `%1` argument in the string was removed the call to `.arg()` is pointless:

```suggestion
            errorReason = tr("An unexpected error occurred when trying to access the server. "
                             "Please try to access it again later or contact your server administrator if the issue continues.");
```

File: src/gui/creds/flow2auth.cpp [hunk 2]
```diff
@@ -253,26 +253,40 @@ QJsonObject Flow2Auth::handleResponse(QNetworkReply *reply)
...
+            qCWarning(lcFlow2auth) << "Error returned from JSON:" << errorFromJson;
         } else if (reply->error() != QNetworkReply::NoError) {
             auto errorStringFromReply = reply->errorString();
             if (const auto hstsError = AbstractNetworkJob::hstsErrorStringFromReply(reply)) {
                 errorStringFromReply = *hstsError;
             }
-            errorReason = tr("There was an error accessing the \"token\" endpoint: <br><em>%1</em>")
+            errorReason = tr("An unexpected error occurred when trying to access the server. "
+                             "Please try to access it again later or contact your server administrator if the issue continues.")
             .arg(errorStringFromReply.toHtmlEscaped());
```
Comment (nilsding) [inline src/gui/creds/flow2auth.cpp]: since the `%1` argument in the string was removed the call to `.arg()` is pointless:
```suggestion
            errorReason = tr("An unexpected error occurred when trying to access the server. "
                             "Please try to access it again later or contact your server administrator if the issue continues.");
```

File: src/libsync/abstractnetworkjob.cpp [hunk 3]
```diff
@@ -533,7 +533,7 @@ QString networkReplyErrorString(const QNetworkReply &reply)
             userFriendlyMessage = QObject::tr("We’re having trouble connecting to the server. Please try again soon. If the issue persists, your server administrator can help you.");
             break;
         case 503: //Service Unavailable
-            userFriendlyMessage = QObject::tr("The server is busy right now. Please try syncing again in a few minutes or contact your server administrator if it’s urgent.");
+            userFriendlyMessage = QObject::tr("The server is busy right now. Please try connecting again in a few minutes or contact your server administrator if it’s urgent.");
```
Comment (nilsding) [inline src/libsync/abstractnetworkjob.cpp:536]: IIRC changing these messages requires some tests to be updated as well

File: src/gui/creds/flow2auth.cpp (hunk 2 above)
Comment (Aiiaiiio) [inline src/gui/creds/flow2auth.cpp]: same here

**Review by Aiiaiiio — CHANGES_REQUESTED** [review]
Please check the placeholders for the args in the error messages.

**Review by nilsding — CHANGES_REQUESTED** [review]

**Review by nilsding — APPROVED** [review]
