### PR TITLE
Only accept folder setup page if overrideLocalDir is set

### LINKED ISSUE #5383: [Bug]: nextcloud 3.6.6 or 3.7.0 rc1 does not allow to choose destination folder
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
nextcloud 3.6.6 o 3.7.0 rc1 non permette di scegliere cartella di destinazione sia nella versione wondows che Linux applicazione qua do attiva alla schermata di scelta cartella di destinazione dopo pochi secondi scompare sceglie di lei di default la cartella dove salvare i dati senza dare il tempo di scegliere una cartella nuova o preesistente. questo ê un problema

### Steps to reproduce

nextcloud 3.6.6 o 3.7.0 rc1 non permette di scegliere cartella di destinazione sia nella versione wondows che Linux applicazione qua do attiva alla schermata di scelta cartella di destinazione dopo pochi secondi scompare sceglie di lei di default la cartella dove salvare i dati senza dare il tempo di scegliere una cartella nuova o preesistente. questo ê un problema

### Expected behavior

nextcloud 3.6.6 o 3.7.0 rc1 non permette di scegliere cartella di destinazione sia nella versione wondows che Linux applicazione qua do attiva alla schermata di scelta cartella di destinazione dopo pochi secondi scompare sceglie di lei di default la cartella dove salvare i dati senza dare il tempo di scegliere una cartella nuova o preesistente. questo ê un problema

### Which files are affected by this bug

All

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.6.6

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
nextcloud 3.6.6 o 3.7.0 rc1 non permette di scegliere cartella di destinazione sia nella versione wondows che Linux applicazione qua do attiva alla schermata di scelta cartella di destinazione dopo pochi secondi scompare sceglie di lei di default la cartella dove salvare i dati senza dare il tempo di scegliere una cartella nuova o preesistente. questo ê un problema
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by camilasan**
Should fix #5383.

For reference please check #5329

### CODE REVIEW

File: src/gui/application.cpp [hunk 1]
```diff
@@ -337,6 +339,19 @@ Application::Application(int &argc, char **argv)
...
+    {
+        // these config values will always be empty after the first client run
+        if (!_overrideServerUrl.isEmpty()) {
+             cfg.setOverrideServerUrl(_overrideServerUrl);
+        }
+
+        if (!_overrideLocalDir.isEmpty()) {
+            cfg.setOverrideLocalDir(_overrideLocalDir);
+        }
+    }
```
Comment (claucambra) [inline src/gui/application.cpp:352]: No variable declarations here, so I would say it makes sense to either remove the block and make it inline with the rest of the method, or to put ConfigFile inside the block so that it no longer takes up resources after the block

**Review by claucambra — APPROVED** [review]
Just a nitpick

**Review by mgallien — APPROVED** [review]

**Comment by szaimen** [comment]
Looks like backports need ro be done manually today...
