### PR TITLE
Fix infinite loading in the share dialog when public link shares are disabled on the server

### LINKED ISSUE #5470: [Bug]: Share dialog exhibits infinite loading when link shares are disabled on the server
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Separate issue from #5411

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not finish loading

### Expected behavior

Share dialog should work even if link shares are disabled on the server

### Which files are affected by this bug

All shareable files

### Operating system

Mac OS

### Which version of the operating system you are running.

13.2

### Package

Other

### Nextcloud Server version

23.0.12

### Nextcloud Desktop Client version

3.7.X

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
We erroneously prevent the share manager from being initialised if public link shares are disabled on the server. Since we can have situations where link shares are disabled but user shares are enabled, this is wrong.

This PR fixes this bug and prevents the placeholder link share from being presented if public link shares are disabled

Fixes #5470

### CODE REVIEW

File: src/gui/filedetails/sharemodel.cpp [hunk 1]
```diff
@@ -405,6 +402,7 @@ void ShareModel::slotSharesFetched(const QList<SharePtr> &shares)
     }
 
     handlePlaceholderLinkShare();
+    Q_EMIT sharesChanged();
```
Comment (mgallien) [inline src/gui/filedetails/sharemodel.cpp:405]: maybe this should be the last line of `ShareModel::handlePlaceholderLinkShare`
that would make sure it is not omitted by its callers

**Review by mgallien — CHANGES_REQUESTED** [review]

File: src/gui/filedetails/sharemodel.cpp (hunk 1 above)
Comment (claucambra) [reply src/gui/filedetails/sharemodel.cpp]: Done

**Review by mgallien — APPROVED** [review]
