### PR TITLE
Fix e2ee upload lock starvation

### LINKED ISSUE #1862: 300 files - each 80K - do not synch
* NC 14.0.4
* End-to-End Encryption 1.0.5
* Windows Desktop Client 2.5.1final (build 20181204)

To reproduce:
* Enabled E2E for folder "TestE2E"
* Copied 300 files with ~80K each to that folder
* Synch does not happen
* Synch with the same files in unencrypted folder "Test" works

Nothing in the NC logs.

grafik

300 files:
[TestE2E.zip](https://github.com/nextcloud/end_to_end_encryption/files/2659936/TestE2E.zip)

### PR DESCRIPTION
**Pull request by er-vin**
Fix #1862

### CODE REVIEW

File: src/libsync/propagateupload.cpp [hunk 1]
```diff
@@ -164,6 +164,48 @@ bool PollJob::finished()
...
+        const auto result = propagator->_remoteFolder;
+        if (result.startsWith('/')) {
+            return result.mid(1);
+        } else {
+            return result;
+        }
+    }();
+    const auto path = _item->_file;
+    const auto slashPosition = path.lastIndexOf('/');
+    const auto parentPath = slashPosition >= 0 ? path.left(path.lastIndexOf('/')) : QString();
```
Comment (misch7) [inline src/libsync/propagateupload.cpp:185]: Better use `path.left(slashPosition)` here.
