### PR TITLE
Fix subfolder encryption scheme

### LINKED ISSUE #774: Files in subfolders of encrypted folders are not encrypted
### Expected behaviour
When adding subfolders to an encrypted folder, these folders should be encrypted as well. The Android app works as expected (version 3.3.1). When creating encrypted subfolders using the Android App they should be decrypted on the desktop client side.

### Actual behaviour
After adding several subfolders and files, the client sync them without encrypting the files in these subfolders. The client doesn't flag the subfolders as encrypted in the GUI as well even if they are encrypted. Encrypted content in subfolders which were created using the Android App are not decrypted. It works with the iOS app, see https://github.com/nextcloud/desktop/issues/816#issuecomment-440694036.

#### files not encrypted
1. encrypt a folder using one of the clients
2. add a subfolder to the encrypted folder
3. add a non-empty text file to this subfolder
4. start synchronization using the desktop client
5. check if the file is encrypted on the server
#### encrypted files not decrypted
1. encrypt a folder
2. add a subfolder using the Android App
3. upload a file to this subfolder
4. synchronize these changes using the desktop client
5. check if the file is decrypted

### Client configuration
Client version: 2.5.0rc1 (build 20181026)

Operating system: macOS High Sierra (10.13.6)

OS language: German

Installation path of client: /Applications/Nextcloud.app

### PR DESCRIPTION
**Pull request by er-vin**
Fix #774

### CODE REVIEW

File: src/libsync/propagateremotemkdir.cpp [hunk 1]
```diff
@@ -36,13 +38,15 @@ void PropagateRemoteMkdir::start()
...
-        return slotStartMkcolJob();
+        slotMkdir();
+        return;
     }
 
     _job = new DeleteJob(propagator()->account(),
         propagator()->_remoteFolder + _item->_file,
         this);
-    connect(_job, SIGNAL(finishedSignal()), SLOT(slotStartMkcolJob()));
+    connect(static_cast<DeleteJob*>(_job.data()), &DeleteJob::finishedSignal,
```
Comment (sbeyer) [inline src/libsync/propagateremotemkdir.cpp:48]: From someone without profound knowledge of the architecture: why `data()`, what does it contain? Is the cast necessary?

**Comment by sbeyer** [comment]
I think this PR provides some basic functionality that should be tested by unit tests.

File: src/libsync/propagateremotemkdir.cpp [hunk 2]
```diff
@@ -75,6 +101,47 @@ void PropagateRemoteMkdir::setDeleteExisting(bool enabled)
...
+
+    if (!account->capabilities().clientSideEncryptionAvailable() ||
+        (!account->e2e()->isFolderEncrypted(remoteParentPath + '/') &&
+         !account->e2e()->isAnyParentFolderEncrypted(remoteParentPath + '/'))) {
+        slotStartMkcolJob();
+        return;
+    }
+
+    // We should be encrypted as well since our parent is
+    _uploadEncryptedHelper = new PropagateUploadEncrypted(propagator(), remoteParentPath, _item);
```
Comment (misch7) [inline src/libsync/propagateremotemkdir.cpp:135]: Might need a parent too

File: src/libsync/propagateupload.cpp [hunk 3]
```diff
@@ -171,18 +171,41 @@ void PropagateUploadFileCommon::setDeleteExisting(bool enabled)
...
+    const auto rootPath = [=]() {
+        const auto result = propagator()->_remoteFolder;
+        if (result.startsWith('/')) {
+            return result.mid(1);
+        } else {
+            return result;
+        }
+    }();
+    const auto path = QString(rootPath + _item->_file);
+    const auto parentPath = path.left(path.lastIndexOf('/'));
```
Comment (misch7) [inline src/libsync/propagateupload.cpp:183]: Looks nearly identical to line 346-355 in `propagatedownload.cpp`, maybe put into a helper to avoid duplication?

Comment (misch7) [reply src/libsync/propagateupload.cpp:183]: Same found in `PropagateRemoteMkdir::slotMkdir()`

Comment (misch7) [reply src/libsync/propagateupload.cpp:183]: Perhaps even more lines of the code, now that I took another look ;)

File: src/libsync/propagateupload.cpp [hunk 4]
```diff
@@ -171,18 +171,41 @@ void PropagateUploadFileCommon::setDeleteExisting(bool enabled)
...
+    const auto remoteParentPath = parentRec._e2eMangledName.isEmpty() ? parentPath : parentRec._e2eMangledName;
+    const auto account = propagator()->account();
+
+    if (!account->capabilities().clientSideEncryptionAvailable() ||
+        !account->e2e()->isFolderEncrypted(remoteParentPath + '/')) {
+        setupUnencryptedFile();
+        return;
     }
+
+    _uploadEncryptedHelper = new PropagateUploadEncrypted(propagator(), remoteParentPath, _item);
```
Comment (misch7) [inline src/libsync/propagateupload.cpp:201]: Perhaps also needs a parent

File: src/libsync/propagateuploadencrypted.h [hunk 5]
```diff
@@ -24,15 +24,15 @@ class FolderMetadata;
...
+ * folderNotEncrypted() if the file is within a folder that's not encrypted.
  *
  */
 
 class PropagateUploadEncrypted : public QObject
 {
   Q_OBJECT
 public:
-    PropagateUploadEncrypted(OwncloudPropagator *propagator, SyncFileItemPtr item);
+    PropagateUploadEncrypted(OwncloudPropagator *propagator, const QString &remoteParentPath, SyncFileItemPtr item);
```
Comment (misch7) [inline src/libsync/propagateuploadencrypted.h:35]: Now I see it should have a parent parameter ;)

File: src/libsync/propagateuploadencrypted.cpp [hunk 6]
```diff
@@ -16,10 +16,11 @@ namespace OCC {
 
 Q_LOGGING_CATEGORY(lcPropagateUploadEncrypted, "nextcloud.sync.propagator.upload.encrypted", QtInfoMsg)
 
-PropagateUploadEncrypted::PropagateUploadEncrypted(OwncloudPropagator *propagator, SyncFileItemPtr item)
-: _propagator(propagator),
- _item(item),
- _metadata(nullptr)
+PropagateUploadEncrypted::PropagateUploadEncrypted(OwncloudPropagator *propagator, const QString &remoteParentPath, SyncFileItemPtr item)
+    : _propagator(propagator)
```
Comment (misch7) [inline src/libsync/propagateuploadencrypted.cpp:20]: Don`t forget parenting here too

File: src/libsync/propagateuploadencrypted.cpp [hunk 7]
```diff
@@ -38,9 +39,7 @@ void PropagateUploadEncrypted::start()
       * If the folder is unencrypted we just follow the old way.
       */
       qCDebug(lcPropagateUploadEncrypted) << "Starting to send an encrypted file!";
-      QFileInfo info(_item->_file);
-      auto getEncryptedStatus = new GetFolderEncryptStatusJob(_propagator->account(),
-                                                           info.path());
+      auto getEncryptedStatus = new GetFolderEncryptStatusJob(_propagator->account(), _remoteParentPath);
```
Comment (misch7) [inline src/libsync/propagateuploadencrypted.cpp:42]: Tonight I really care for poor variable kids without parents ^^

File: src/libsync/propagatorjobs.cpp [hunk 8]
```diff
@@ -156,6 +158,36 @@ void PropagateLocalMkdir::start()
...
+    const auto rootPath = [=]() {
+        const auto result = propagator()->_remoteFolder;
+        if (result.startsWith('/')) {
+            return result.mid(1);
+        } else {
+            return result;
+        }
+    }();
+    const auto remotePath = QString(rootPath + _item->_file);
+    const auto remoteParentPath = remotePath.left(remotePath.lastIndexOf('/'));
```
Comment (misch7) [inline src/libsync/propagatorjobs.cpp:170]: Same repeated code pattern again ;p

File: src/libsync/propagateremotemkdir.cpp (hunk 1 above)
Comment (er-vin) [reply src/libsync/propagateremotemkdir.cpp:48]: _job is a QPointer<AbstractNetworkJob> so we need to downcast back to the DeleteJob we just stored in there. There'd have been nicer ways of doing this but I'm aiming for the minimal changes possible for now.

**Comment by er-vin** [comment]
> I think this PR provides some basic functionality that should be tested by unit tests.

Oh hell yes... I totally agree there. Didn't go for those yet for a couple of reasons though: a) we're lacking a lot in the facilities to test that area at all, b) behavior will change again in further PRs and c) it's all nicely coupled and with the crypto involved it brings its own challenges (at best right now we could shoot for integration tests for which again we got no facilities...). I hate that situation but it's almost a project in itself to get it all sorted to have a proper test pyramid.

I hope to still have some time to get all that to grow once we're closer to release (famous last words...).

File: src/libsync/clientsideencryptionjobs.cpp [hunk 9]
```diff
@@ -35,6 +35,7 @@ void GetFolderEncryptStatusJob::start()
 	req.setPriority(QNetworkRequest::HighPriority);
 	req.setRawHeader("OCS-APIREQUEST", "true");
     req.setHeader(QNetworkRequest::ContentTypeHeader, QByteArrayLiteral("application/xml"));
+    req.setRawHeader("Depth", "infinity");
 
 	QByteArray xml = R"(<d:propfind xmlns:d="DAV:"> <d:prop xmlns:nc="http://nextcloud.org/ns"> <nc:is-encrypted/> </d:prop> </d:propfind>)";
 	auto *buf = new QBuffer(this);
```
[the remark this answers is not in the document]
Comment (er-vin) [reply src/libsync/clientsideencryptionjobs.cpp:41]: Yes... the E2EE code has an interesting mix of 2 spaces, 4 spaces and tabs (*gasp*) indents...

I'm going the road of fixing it one line at a time instead of running clang-format on it. That explains what you see and I hate it.

File: src/libsync/clientsideencryptionjobs.h [hunk 10]
```diff
@@ -293,7 +293,7 @@ public slots:
 	bool finished() override;
 
 signals:
-	void encryptStatusReceived(const QMap<QString, bool> folderMetadata2EncryptionStatus);
+    void encryptStatusReceived(const QHash<QString, bool> folderMetadata2EncryptionStatus);
     void encryptStatusFolderReceived(const QString &folder, bool isEncrypted);
 	void encryptStatusError(int statusCode);
```
[the remark this answers is not in the document]
Comment (er-vin) [reply src/libsync/clientsideencryptionjobs.h:298]: Yes... annoying heh? ;-)

File: src/libsync/owncloudpropagator.cpp [hunk 11]
```diff
@@ -510,7 +510,15 @@ void OwncloudPropagator::start(const SyncFileItemVector &items,
 
     connect(_rootJob.data(), &PropagatorJob::finished, this, &OwncloudPropagator::emitFinished);
 
-    scheduleNextJob();
+    // If needed, make sure we have up to date E2E information before scheduling the first job
+    // otherwise we start right away
+    if (_account->capabilities().clientSideEncryptionAvailable()) {
+        _account->e2e()->fetchFolderEncryptedStatus();
+        connect(_account->e2e(), &ClientSideEncryption::folderEncryptedStatusFetchDone,
```
[the remark this answers is not in the document]
Comment (er-vin) [reply src/libsync/owncloudpropagator.cpp:517]: No chance of this causing a problem with the code as it is today (signal will be emitted after at least one going back to the event loop so the connect would be done). Still better safe than sorry if said code changes.

File: src/libsync/propagateupload.cpp (hunk 3 above)
Comment (er-vin) [reply src/libsync/propagateupload.cpp:183]: Correct, and it's getting worse in the other PR I'm working on at the moment.

I'm aware of it and letting it slide on purpose for now, it looks like that as we take more scenarios into account there might be more variation of that code. Also I didn't find a proper place to put it in (yet) without inducing even more coupling.

So I won't address this just yet.

**Comment by sbeyer** [comment]
> I hate that situation but it's almost a project in itself to get it all sorted to have a proper test pyramid.

Yes, I noticed this. Has to be done sooner or later, though. :-)

**Comment by er-vin** [comment]
> > I hate that situation but it's almost a project in itself to get it all sorted to have a proper test pyramid.
> 
> Yes, I noticed this. Has to be done sooner or later, though. :-)

I wish it was done two years ago TBH. ;-)
