### PR TITLE
Bugfix/rw folders broken

### LINKED ISSUE #6741: [Bug]: Read-Only permission after adding Downloads folder to Nextcloud-synchronisation
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The problem happened on two different devices with Windows 10 and Window 11.

I added the Downloads-Folder as a seperated synchronisation-folder to the desktop client. After a while the downloads-folder was read only. It was not possible to add new files and folders. It was also not possible to change the persmission back to read/write (with and without admin privileges). Even after removing the folder from the desktop client (synchronisation) so folder was still read only.

I found this work-around to enable write-access again: https://answers.microsoft.com/en-us/windows/forum/all/unable-to-delete-folder-as-administrator-requires/ae5b6cf6-dae5-49b9-83db-1435d41749a9?page=2

```
Ok I found the answer:
First, rename the file so that it has an unknown extension
In the advanced permissions, change the owner to everyone
Then move the files to a folder you have full control of
Go back to permissions and set the owner as your account name
close the window
Go back to permissions and enable inheritance
you can then delete the file
Repeat for every file you wish to delete
```

The Downloads-Folder is a system folder. It was not a good idea to delete the folder.

Yesterday I had this problem on the Windows 10 device. After fixing the problem yesterday I tried it again and since than, the synchronisation works without any problems.

Today I tried it on the Windows 11 device with the same problem. I also added the Downloads-Folder to the synchronisation. After a while the same problem.

### Steps to reproduce

1. Add the downloads-folder (c:\users\name\Downloads) to the desktop-client as a new folder-syncronisation (root folder on the Nextcloud-Server)
2. The synchronisation starts synching without problems.
3. After a while I get the error message from Desktop Client that the folder is read only.

### Expected behavior

No changing persmissions to the folder.

### Which files are affected by this bug

Autoruns.zip

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10, Windows 11

### Package

Appimage

### Nextcloud Server version

28.0.5

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #6796: [Bug]: Synchronisation error - Permission denied
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On Linux, when synchronising a file that has been modified by someone else and is only shared with read-only permission, the synchronisation gives an error, "permission denied".

It is because the Nextcloud client sets the permission of the file to read-only and is not able to write it again locally when it is modified.

### Steps to reproduce

1. User A create a file
2. Share the file to user B with read-only permission
3. User B synchronises the file
4. Use A modifies the file
5. User B has an error "permission denied" when doing the synchronisation again.

### Expected behavior

The client should set the permissions to read-write, modify the file and set again the local permissions to read-only.

### Which files are affected by this bug

All files with read-only permission that are modified by someone else

### Operating system

Linux

### Which version of the operating system you are running.

Fedora Linux 39

### Package

Appimage

### Nextcloud Server version

28.0.3.2

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #6824: [BUG] Linux client fails to sync read-write shares subfolders of read-only shared folder
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

User U1 has a folder structure as MAIN/SUB-RO and MAIN/SUB-RW

User U1 shares with user U2:
- MAIN as read-only
- SUB-RW as read-write

U2 sees and syncs at his root both MAIN and SUB-RW

U2 can NOT make modifications in SUB-RW.
The client returns a failure in the sync activity shown for MAIN/SUB-RW

### Steps to reproduce

User U2 makes any modification in SUB-RW

The client returns a failure in the sync activity shown for MAIN/SUB-RW

### Expected behavior

 U2 can make any modification in SUB-RW

### Which files are affected by this bug

Any

### Operating system

Linux

### Which version of the operating system you are running.

Fedora  40

### Package

Distro package manager

### Nextcloud Server version

29.0.2

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Cannot find any error nor warning
```

### Additional info

All works when doing things from the web interface.
So it seems that is only the latest Linux Nextcloud-client update, which attempts to upload a change to the read-only master folder, rather than to the current shared subfolder (with modifications rights).

### PR DESCRIPTION
**Pull request by claucambra**
Closes #6741
Closes #6824
Closes #6796

### CODE REVIEW

File: src/libsync/filesystem.cpp [hunk 1]
```diff
@@ -451,22 +451,18 @@ bool FileSystem::setFolderPermissions(const QString &path,
...
 #endif
 
-#if !defined(Q_OS_MACOS) || __MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_15
     try {
         switch (permissions) {
         case OCC::FileSystem::FolderPermissions::ReadOnly:
             break;
         case OCC::FileSystem::FolderPermissions::ReadWrite:
-            std::filesystem::permissions(path.toStdWString(), std::filesystem::perms::owner_write, std::filesystem::perm_options::add);
+            std::filesystem::permissions(stdStrPath, writePerms, std::filesystem::perm_options::add);
```
Comment (mgallien) [inline src/libsync/filesystem.cpp:459]: I am not sure how we should deal with this and users possibly have specific `umask`

**Review by mgallien — APPROVED** [review]

**Comment by PhilippSchlesinger** [comment]
@claucambra there is a recent folder permissions bug https://github.com/nextcloud/desktop/issues/6863 regarding the changes in this PR.
