### PR TITLE
fix(asyncimageresponse): enhance check for received SVG response 

### LINKED ISSUE #9681: [Bug]: v33 apps menu rendering is bugged - large icons, flickering menu item sizes (macOS)
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When opening the apps dropdown menu from the Nextcloud app popup, the menu items are flickering between different sizes, some icons are not being sized correctly, and the menu is almost unusable.

### Steps to reproduce

1. Open the Nextcloud popup from the menu bar
2. Open the apps dropdown

### Expected behavior

All items should be correctly sized, with icons at the correct size, and the items should be static and not flickering

### Which files are affected by this bug

-

### Operating system

macOS

### Which version of the operating system you are running.

Sonoma 14.8.3 (23J220)

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

33.0.0

### Nextcloud Desktop Client version

33.0.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.16.3 to 3.17.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
N/A
```

### Additional info

Screenshot:

Image

Video:

https://github.com/user-attachments/assets/590837a6-153c-4d4f-bdfc-db73bd09c422

Debug archive:

[nextcloud-desktop-debug 2.zip](https://github.com/user-attachments/files/26214917/nextcloud-desktop-debug.2.zip)

### LINKED ISSUE #9685: [Bug]: Version 33.0.0 and Cookbook app causing memory leak on desktop client.
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Having the cookbook extension enabled on a Nextcloud server which is having files synced via the Desktop Client causes the Desktop Client to leak memory.
It also causes consistent CPU usage (~4% on a Ryzen 7 5800X, plus additional usage from Windows Defender scanning the created log files) , disk usage (~1.5MB/s, presumably writing to logs), and network usage (~120KB/s)
See image for resource usage with this bug. Note, the memory usage continues to increase (I've seen it as high as 7GB)
Image

### Steps to reproduce

1. Enable [Cookbook](https://apps.nextcloud.com/apps/cookbook) on a Nextcloud server
2. Ensure a folder is being synced via the Desktop Client
3. Switch from "No proxy" to "Use system proxy" (without this, it may not work from just installing the app, this seems to refresh something)
4. Wait for memory usage to slowly increase.

### Expected behavior

No memory leak, this app doesn't sync anything to desktop anyways.
See image for usual Desktop Client resource usage
Image

### Which files are affected by this bug

gui\creds\webflowcredentials.cpp, src\libsync\accessmanager.cpp

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official Windows MSI

### Nextcloud Server version

32.0.6

### Nextcloud Desktop Client version

33.0.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.16.3 to 3.17.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
There are no server logs from around the time that this bug occurs.
```

### Additional info

Switching from "No proxy" to "Use system proxy" (or vice verca) clears the memory used, 
I've only attached a portion of the desktop logs, as it is the same thing for over 39k lines, over the span of 4 minutes.

[log_upload.log](https://github.com/user-attachments/files/26223834/log_upload.log)

### LINKED ISSUE #9689: [Bug]: v33.0.0 Windows Release - High Disk IO
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I've removed the client, back to 4.0.8 for the time beaing, but task manager and resource manager reported 50+% utilization disk usage while just having v33 open.  Even with syncing paused.
Rolled back to 4.0.8, no issues.

### Steps to reproduce

Install v 33.0 client on windows.
See disk usage spike in task manager, open resource monitor, see that nextcloud client writing to C:\$LOGFile and C:\$MFT constant 2-4MB/s
 

### Expected behavior

With synching paused, client app should not be writing to the disk in large volume

### Which files are affected by this bug

as reported by Resource Monitor, C:\$LOGFile and C:\$MFT

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

33.0.0

### Nextcloud Desktop Client version

33.0.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.16.3 to 3.17.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nilsding**
Some app icon SVGs do not start with `<svg` but with e.g. `<?xml` and could include some additional metadata (e.g. a generator comment or licence header ...) before the expected `<svg` tag ... therefore let's check whether the reply is an SVG by peeking at the *content-type* header and the first 512 bytes of the response if the header was not enough.

Resolves #9685, resolves #9689, resolves #9681.

fix confirmed on Windows 11 and on Linux (with `QT_QPA_PLATFORMTHEME=gtk3` as the KDE Plasma one did not run into that)

### CODE REVIEW

File: src/gui/tray/asyncimageresponse.cpp [hunk 1]
```diff
@@ -109,36 +111,43 @@ void AsyncImageResponse::processNetworkReply(QNetworkReply *reply)
...
+
+    // check whether the reply might be an SVG by looking at the content type and the first 512 bytes of the response for `<svg`.
+    // Some graphics programs export SVGs that begin with `<?xml version="1.0" [...]` and/or include some comments after that (e.g.
+    // `<!-- Generator: ...`), so we can't rely on just the response to start with `<svg`.
+    if (const auto contentTypeHeader = reply->header(QNetworkRequest::ContentTypeHeader);
+        !(contentTypeHeader.toString().startsWith("image/svg"_ba) || imageData.first(qMin(imageData.size(), 512)).contains("<svg"_ba))) {
+        // Not an SVG: let's let QImage deal with the response.
+        setImageAndEmitFinished(QImage::fromData(imageData).scaled(_requestedImageSize));
+        return;
+    }
```
Comment (mgallien) [inline src/gui/tray/asyncimageresponse.cpp]: should we not stop trying to guess on our own and use `QMimeDatabase::mimeTypeForData(const QByteArray &data)` ?

Comment (nilsding) [reply src/gui/tray/asyncimageresponse.cpp]: good idea, just replaced the detection with that.
