### PR TITLE
fix: try to avoid displaying duplicate server notifications in activity list

### LINKED ISSUE #6624: [Bug]: Talk duplicated notifications
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Multiple of the same talk notification are displayed/listed.

### Steps to reproduce

1. Run the latest desktop client
2. Check the activities list

Screenshot 2024-04-12 at 16 26 23

### Expected behavior

There should be only one notification.

### Which files are affected by this bug

none

### Operating system

Mac OS

### Which version of the operating system you are running.

Mac OS 14.4

### Package

Other

### Nextcloud Server version

latest

### Nextcloud Desktop Client version

3.13.0-rc2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by nilsding**
Resolves #6624 

includes some cleanup in UserModel and ActivityListModel

### CODE REVIEW

File: src/gui/tray/activitylistmodel.cpp [hunk 1]
```diff
@@ -523,18 +523,37 @@ void ActivityListModel::activitiesReceived(const QJsonDocument &json, int status
...
+    if (filteredList.isEmpty()) {
         return;
     }
 
     const auto startRow = _finalList.count();
 
-    beginInsertRows({}, startRow, startRow + activityList.count() - 1);
-    for(const auto &activity : activityList) {
+    beginInsertRows({}, startRow, startRow + filteredList.count() - 1);
+    for(const auto &activity : filteredList) {
```
Comment (Aiiaiiio) [inline src/gui/tray/activitylistmodel.cpp]: Qt complains about possible detach.
```suggestion
    for(const auto &activity : std::as_const(filteredList)) {

File: src/gui/tray/usermodel.cpp [hunk 2]
```diff
@@ -232,43 +224,41 @@ void User::showDesktopTalkNotification(const Activity &activity)
...
     });
 
-    if(toNotifyList.count() > 2) {
-        showDesktopNotification(toNotifyList);
+    if (toNotifyList.isEmpty()) {
         return;
     }
 
-    for (const auto &activity : std::as_const(toNotifyList)) {
+    if (toNotifyList.size() == 1) {
```
Comment (Aiiaiiio) [inline src/gui/tray/usermodel.cpp:249]: I don't understand this part. Why is it different if we have only 1 activity to notify about versus more?

Comment (nilsding) [reply src/gui/tray/usermodel.cpp:249]: `User::showDesktopNotification(const Activity &activity)` will add the notification to the activity list and also display a system notification, whereas `User::showDesktopNotification(const ActivityList &activityList)` only ends up adding those to the activity list.  It's weird.
