### PR TITLE
Only show mnemonic request dialog when user explicitly wants to enable E2EE

### LINKED ISSUE #4778: [Bug]: at the second configuration of an account E2EE mnemonic is asked even if it has never been configured before
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Mnemonic for E2E encryption is asked at NC desktop client startup, event if the E2EE for the user has never been enabled.

### Steps to reproduce

1. On an instance with E2E enabled.
2. Create a user.
3. Install desktop client.
4. Connect the desktop client to the user account.
5. Wait for sync is complete.
6. Remove the user account from the desktop client
7. Exit Nextcloud desktop client
8. Wait a bit
9. Delete synchronisation files
10. Restart NC Synchronisation client
11. Reconfigure the user account.
12. The NC desktop client asks you for the E2EE mnemonic.

### Expected behavior

If I don't choose to enable E2EE on my account, the desktop client shouldn't ask me for the E2EE mnemonic on the second configuration, as I don't have it, and it should not exist.

### Which files are affected by this bug

not related to a file

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

c.nc.com

### Nextcloud Desktop Client version

3.5.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
This stops the user getting spammed with annoying pop-ups on launch asking for the mnemonic when they have no intention of enabling encryption on their current system/account

Closes #4778 

Signed-off-by: Claudio Cambra <claudio.cambra@nextcloud.com>

### CODE REVIEW

File: src/libsync/account.h [hunk 1]
```diff
@@ -304,10 +304,13 @@ class OWNCLOUDSYNC_EXPORT Account : public QObject
     void setE2eEncryptionKeysGenerationAllowed(bool allowed);
     [[nodiscard]] bool e2eEncryptionKeysGenerationAllowed() const;
 
+    [[nodiscard]] bool askUserForMnemonic() const;
```
Comment (mgallien) [inline src/libsync/account.h:307]: why not also making it a real Qt property ?

File: src/libsync/clientsideencryption.cpp [hunk 2]
```diff
@@ -1248,6 +1248,12 @@ void ClientSideEncryption::encryptPrivateKey(const AccountPtr &account)
 }
 
 void ClientSideEncryption::decryptPrivateKey(const AccountPtr &account, const QByteArray &key) {
+    if (!account->askUserForMnemonic()) {
+        qCInfo(lcCse) << "Not allowed to ask user for mnemonic";
```
Comment (mgallien) [inline src/libsync/clientsideencryption.cpp:1252]: I would go with debug level otherwise we spam with too many log output in Info level

Comment (claucambra) [reply src/libsync/clientsideencryption.cpp]: Changed to a `qCDebug`

File: src/libsync/account.h (hunk 1 above)
Comment (claucambra) [reply src/libsync/account.h:315]: I didn't think it necessary -- made it one now, however

**Review by mgallien — APPROVED** [review]
