### PR TITLE
Accept valid lsColJob reply XML content types

### LINKED ISSUE #4873: [Bug]: client does not work when the server is forcing text/xml content type
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

As seen here: https://github.com/nextcloud/desktop/blob/eeb0d20a7f2e0829799785412e6c0e034266e534/src/libsync/discoveryphase.cpp#L591

There is a issue in the source code, as it is only expecting `application/xml` but a server may force to send `text/xml` (for example when you have a security proxy or something else).

Also if the header is `Content-Type: application/xml; charset="utf-8"` (note the quotes), the client will fail, even though this is perfectly valid header, as seen in the RFC: https://httpwg.org/specs/rfc7231.html#data.type

The NextCloud client should accept both text/xml and application/xml, as well as not failing if the charset value is using quotes.

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

Accepting text/xml

### Which files are affected by this bug

all

### Operating system

Linux

### Which version of the operating system you are running.

Debian

### Package

Other

### Nextcloud Server version

Doesn't matter

### Nextcloud Desktop Client version

ALL

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
It seems we refuse some XML content type formats even though they are still valid and can be parsed by the parser

Fixes #4873

Signed-off-by: Claudio Cambra <claudio.cambra@gmail.com>

### CODE REVIEW

File: src/libsync/discoveryphase.cpp [hunk 1]
```diff
@@ -583,14 +583,20 @@ void DiscoverySingleDirectoryJob::lsJobFinishedWithoutErrorSlot()
...
 void DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply *r)
 {
-    QString contentType = r->header(QNetworkRequest::ContentTypeHeader).toString();
-    int httpCode = r->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
+    const QString contentType = r->header(QNetworkRequest::ContentTypeHeader).toString();
+    const bool invalidContentType = !contentType.contains("application/xml; charset=utf-8") &&
+                                    !contentType.contains("application/xml; charset=\"utf-8\"") &&
+                                    !contentType.contains("text/xml; charset=utf-8") &&
+                                    !contentType.contains("text/xml; charset=\"utf-8\"");
+    const int httpCode = r->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
```
Comment (mgallien) [inline src/libsync/discoveryphase.cpp:591]: `const auto`

File: src/libsync/networkjobs.cpp [hunk 2]
```diff
@@ -395,9 +395,14 @@ bool LsColJob::finished()
     qCInfo(lcLsColJob) << "LSCOL of" << reply()->request().url() << "FINISHED WITH STATUS"
                        << replyStatusString();
 
-    QString contentType = reply()->header(QNetworkRequest::ContentTypeHeader).toString();
-    int httpCode = reply()->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
-    if (httpCode == 207 && contentType.contains("application/xml; charset=utf-8")) {
+    const QString contentType = reply()->header(QNetworkRequest::ContentTypeHeader).toString();
+    const int httpCode = reply()->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
+    const bool validContentType = contentType.contains("application/xml; charset=utf-8") ||
```
Comment (mgallien) [inline src/libsync/networkjobs.cpp:400]: `const auto`

File: src/libsync/discoveryphase.cpp [hunk 3]
```diff
@@ -583,14 +583,20 @@ void DiscoverySingleDirectoryJob::lsJobFinishedWithoutErrorSlot()
 
 void DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply *r)
 {
-    QString contentType = r->header(QNetworkRequest::ContentTypeHeader).toString();
-    int httpCode = r->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
+    const QString contentType = r->header(QNetworkRequest::ContentTypeHeader).toString();
+    const bool invalidContentType = !contentType.contains("application/xml; charset=utf-8") &&
+                                    !contentType.contains("application/xml; charset=\"utf-8\"") &&
```
Comment (mgallien) [inline src/libsync/discoveryphase.cpp:588]: what can produce `"utf-8"` ?
looks like a bogus value to me (see https://www.rfc-editor.org/rfc/rfc7303.html#page-15)

Comment (claucambra) [reply src/libsync/discoveryphase.cpp:588]: It's a valid format: https://httpwg.org/specs/rfc7231.html#data.type

Comment (mgallien) [reply src/libsync/discoveryphase.cpp:588]: OK, thanks for finding the reference as I could not find it

File: src/libsync/networkjobs.cpp (hunk 2 above)
Comment (claucambra) [reply src/libsync/networkjobs.cpp]: Changed

**Review by mgallien — APPROVED** [review]
