### PR TITLE
Bugfix/conflict resolution when selecting folder

### LINKED ISSUE #4904: [Bug]: conflict resolution for existing folder when setting up sync connection is broken
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The resolution thing for an existing server doesn't work - it detects a folder exists, gives me the options of what to do (overwrite or sync contents) but the 'connect' button will stay grey.

Screenshot 2022-09-06 at 21 57 55

### Steps to reproduce

1. create a new account
2. pick a non-empty folder to sync with the server
3. choose a resolution - any - you won't be able to proceed (at least not that I could find out)

### Expected behavior

When you pick a resolution, you should be able to proceed.
...

### Which files are affected by this bug

none

### Operating system

Mac OS

### Which version of the operating system you are running.

latest

### Package

Other

### Nextcloud Server version

25beta3

### Nextcloud Desktop Client version

3.6RC2

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
not really relevant I think
```

### Additional info

Not sure if client logs etc are relevant?

### PR DESCRIPTION
**Pull request by allexzander**
Fix #4904

### CODE REVIEW

File: src/gui/folderman.cpp [hunk 1]
```diff
@@ -945,11 +945,15 @@ void FolderMan::runEtagJobIfPossible(Folder *folder)
 
 void FolderMan::slotAccountRemoved(AccountState *accountState)
 {
+    QVector<Folder *> foldersToRemove;
     for (const auto &folder : qAsConst(_folderMap)) {
         if (folder->accountState() == accountState) {
-            folder->onAssociatedAccountRemoved();
```
Comment (mgallien) [inline src/gui/folderman.cpp:950]: why do you remove this call ?
sounds like we were doing some stuff with the VFS ?

Comment (allexzander) [reply src/gui/folderman.cpp:950]: @mgallien Yes, we're doing it here. But, we're also doing it in `void Folder::wipeForRemoval()`, so, this is a duplicate, and, the worst thing, it leads to a crash in CfAPI unregister code because of calling `_vfs->stop();` and `_vfs->unregisterFolder();` 2 times, while we only need to call it once. And now, with my other change, it is all being called within the  `void Folder::wipeForRemoval()`, which is just enough.

Comment (allexzander) [reply src/gui/folderman.cpp:950]: @mgallien And one more detail, `void FolderMan::removeFolder(Folder *f)` will call `void Folder::wipeForRemoval()` always

**Review by mgallien — APPROVED** [review]
