### PR TITLE
Fix #2243

### LINKED ISSUE #2243: URL of default Talk button is wrong.
### Expected behaviour
Clicking on the Talk button in the main window should open the browser and the Talk app.

### Actual behaviour
The link that is openend is .../apps/spreed/ instead of .../index.php/apps/spreed/

### Steps to reproduce
1. clicking on the Talk button
2. Check url

### Client configuration
Client version:
Default 2.7RC1

Operating system:
MacOS

OS language:
english

Qt version used by client package (Linux only, see also Settings dialog):
default

Client package (From Nextcloud or distro) (Linux only):
official build

Installation path of client:
default

### PR DESCRIPTION
**Pull request by camilasan**
#2243

### CODE REVIEW

File: src/gui/tray/UserModel.cpp [hunk 1]
```diff
@@ -486,6 +486,11 @@ bool User::serverHasTalk() const
     return _account->hasTalk();
 }
 
+AccountApp *User::talkApp() const
+{
+    return _account->findApp(QLatin1String("spreed"));
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp:491]: You're merely moving code around here, but good opportunity to use `QStringLiteral` instead of `QLatin1String` here.

File: src/gui/tray/UserModel.cpp [hunk 2]
```diff
@@ -646,11 +651,12 @@ Q_INVOKABLE void UserModel::openCurrentAccountTalk()
...
         return;
 
-    QString url = _users[_currentUserId]->server(false) + "/apps/spreed";
-    if (!(url.contains("http://") || url.contains("https://"))) {
-        url = "https://" + _users[_currentUserId]->server(false) + "/apps/spreed";
+    auto talkApp = _users[_currentUserId]->talkApp();
+    if(talkApp){
+        QDesktopServices::openUrl(talkApp->url());
+    } else {
+        qCInfo(lcActivity) << "The Talk app was not found on the server.";
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp]: nitpick: I'd go for warning instead of info. It's not really supposed to happen, if we got in that else something was wrong in the caller.

File: src/gui/tray/UserModel.cpp [hunk 3]
```diff
@@ -646,11 +651,12 @@ Q_INVOKABLE void UserModel::openCurrentAccountTalk()
     if (_users.isEmpty())
         return;
 
-    QString url = _users[_currentUserId]->server(false) + "/apps/spreed";
-    if (!(url.contains("http://") || url.contains("https://"))) {
-        url = "https://" + _users[_currentUserId]->server(false) + "/apps/spreed";
+    auto talkApp = _users[_currentUserId]->talkApp();
+    if(talkApp){
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp:647]: Missing space after if and before opening curly brace, should be: `if (talkApp) {`

File: src/gui/tray/UserModel.cpp [hunk 4]
```diff
@@ -655,7 +647,8 @@ Q_INVOKABLE void UserModel::openCurrentAccountTalk()
     if(talkApp){
         QDesktopServices::openUrl(talkApp->url());
     } else {
-        qCInfo(lcActivity) << "The Talk app was not found on the server.";
+        qCInfo(lcActivity) << "The Talk app is not enabled on " <<
+                              _users[_currentUserId]->server();
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp:651]: I'd say use `currentUser()` instead of `_users[_currentUserId]`.

File: src/gui/tray/UserModel.cpp [hunk 5]
```diff
@@ -646,11 +643,13 @@ Q_INVOKABLE void UserModel::openCurrentAccountTalk()
     if (_users.isEmpty())
         return;
 
-    QString url = _users[_currentUserId]->server(false) + "/apps/spreed";
-    if (!(url.contains("http://") || url.contains("https://"))) {
-        url = "https://" + _users[_currentUserId]->server(false) + "/apps/spreed";
+    auto talkApp = _users[_currentUserId]->talkApp();
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp:646]: I'd say use `currentUser()` instead of `_users[_currentUserId]`. We're duplicating that logic everywhere inside `UserModel` otherwise.

File: src/gui/tray/UserModel.cpp [hunk 6]
```diff
@@ -643,14 +648,16 @@ Q_INVOKABLE void UserModel::openCurrentAccountLocalFolder()
...
         return;
 
-    QString url = _users[_currentUserId]->server(false) + "/apps/spreed";
-    if (!(url.contains("http://") || url.contains("https://"))) {
-        url = "https://" + _users[_currentUserId]->server(false) + "/apps/spreed";
+    auto talkApp = currentUser()->talkApp();
+    if (talkApp) {
+        QDesktopServices::openUrl(talkApp->url());
+    } else {
+        qCWarning(lcActivity) << "The Talk app is not enabled on " <<
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp:650]: Somehow didn't notice it the previous time but you don't need the space before the closing double quote. They're added for you automatically, also you can probably have this on a single line.

File: src/gui/tray/UserModel.cpp [hunk 7]
```diff
@@ -643,14 +648,16 @@ Q_INVOKABLE void UserModel::openCurrentAccountLocalFolder()
...
 Q_INVOKABLE void UserModel::openCurrentAccountTalk()
 {
-    if (_users.isEmpty())
+    if (!currentUser())
         return;
 
-    QString url = _users[_currentUserId]->server(false) + "/apps/spreed";
-    if (!(url.contains("http://") || url.contains("https://"))) {
-        url = "https://" + _users[_currentUserId]->server(false) + "/apps/spreed";
+    auto talkApp = currentUser()->talkApp();
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp:646]: nitpick: `const auto`?

I live by aggressively using const ;-)

File: src/gui/tray/UserModel.cpp [hunk 8]
```diff
@@ -871,9 +863,10 @@ void UserAppsModel::buildAppList()
     }
 
     if (UserModel::instance()->appList().count() > 0) {
+        auto talkApp = UserModel::instance()->currentUser()->talkApp();
```
Comment (er-vin) [inline src/gui/tray/UserModel.cpp:866]: nitpick: const auto

File: src/gui/tray/UserModel.cpp (hunk 7 above)
Comment (camilasan) [reply src/gui/tray/UserModel.cpp]: "aggressively using const" would be a great tattoo or sticker.
