### PR TITLE
avoid detecting permissions to be invalid on linux NTFS file system

### LINKED ISSUE #7613: [Bug]: Version 3.15.0 seems to be stuck in an infinite loop during "Checking folder changes". HDD is running hot.
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Debian 12 Linux, Gnome DE, Nextcloud Desktop client 3.15.0

Version 3.15.0 seems to be stuck in an infinite loop during "Checking folder changes". HDD is running hot. I've let it run for 30 minutes and more, just to see if it eventually stops at some point. It doesn't.

General startup of the client seems fine. File sync runs through fine. After that it goes into "Checking folder changes" - that's where it gets stuck in the loop. Reaction times get very slow on every action I take in the client. Gnome offers generic "App not responding, should I kill it or wait" warning.  With every older Client (e.g. 3.14.3) it works just fine. So there seems to be some regression introduced in 3.15.0...

If there's any more info I can provide, please let me know.

### Steps to reproduce

Startup Nextcloud-3.15.0-x86_64.AppImage
Wait for the app to start up...

### Expected behavior

normal startup without trashing my HDD...

### Which files are affected by this bug

folder

### Operating system

Linux

### Which version of the operating system you are running.

Debian 12

### Package

Official Linux AppImage

### Nextcloud Server version

30.0.3

### Nextcloud Desktop Client version

3.15.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by mgallien**
Close #7613

### CODE REVIEW

**Comment by luk-brue** [comment]
I built this branch from source on Linux Mint 21.3 Cinnamon and tested it with some folders on NTFS partitions (different partition than the OS). It works sometimes, which was great! But then it stops working and does not sync new files. Either it is stuck in Offline or it is stuck in "preparing sync..." for hours and nothing happens, even though new files are in the folder. Sometimes it also says "checking folder for new files..." The only solution to make sync work again on NTFS partitions is to remove the accounts and re-add them, then it works sometimes. However, syncing a folder on the same partition as the OS, normal ext4 filesystem, is working fine. 

Also weird, When I add an account, I have to authenticate once when I add it and once more when I reboot the machine for the first time afterwards. 
I don't know if this is on my side (Qt communicating with keyring) or the client side. 

Built with Qt 6.8.2.
I hope this little experience review will help in the developing process, you are doing an awesome job! If you have more questions, I can try to answer them.

**Comment by nilsding** [comment]
> Also weird, When I add an account, I have to authenticate once when I add it and once more when I reboot the machine for the first time afterwards.

this should be fixed with #7768 which was merged after this PR was created (and this branch is currently out-of-date).  Should be fine on latest master...

**Comment by Kleisli** [comment]
@mgallien is there anything I could do to support you fixing this bug?
Should I test the AppImage from Jan 10? Or do you need Debug-Logs?

File: src/libsync/syncengine.cpp [hunk 1]
```diff
@@ -632,6 +633,19 @@ void SyncEngine::startSync()
     _remnantReadOnlyFolders.clear();
 
     _discoveryPhase = std::make_unique<DiscoveryPhase>();
+
+#if defined Q_OS_LINUX
```
Comment (mgallien) [inline src/libsync/syncengine.cpp]:
```suggestion
#if !defined Q_OS_WINDOWS
```

**Comment by mgallien** [comment]
should now works fine
I tested it with fuse ntfs-3g driver on a recent Debian sid

File: src/csync/vio/csync_vio_local.h [hunk 2]
```diff
@@ -18,8 +18,8 @@ class Vfs;
 
 csync_vio_handle_t OCSYNC_EXPORT *csync_vio_local_opendir(const QString &name);
 int OCSYNC_EXPORT csync_vio_local_closedir(csync_vio_handle_t *dhandle);
-std::unique_ptr<csync_file_stat_t> OCSYNC_EXPORT csync_vio_local_readdir(csync_vio_handle_t *dhandle, OCC::Vfs *vfs);
+std::unique_ptr<csync_file_stat_t> OCSYNC_EXPORT csync_vio_local_readdir(csync_vio_handle_t *dhandle, OCC::Vfs *vfs, bool checkPermissionsValidity);
 
-int OCSYNC_EXPORT csync_vio_local_stat(const QString &uri, csync_file_stat_t *buf);
+int OCSYNC_EXPORT csync_vio_local_stat(const QString &uri, csync_file_stat_t *buf, bool checkPermissionsValidity);
```
Comment (nilsding) [inline src/csync/vio/csync_vio_local.h:26]: this needs to be adapted in the `csync_vio_local_win.cpp` as well

Comment (mgallien) [reply src/csync/vio/csync_vio_local.h:26]: done now
