### PR TITLE
when moving a file, checks that it exists at origin or destination

### LINKED ISSUE #6462: [Bug]: data loss when moving files between 2 group folders if the destination one is also directly shared with the user
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

So user has 2 group folders `groupOrigin` and `groupDestination`.
Group folder `groupDestination` is also directly shared with name `directShareGroupDestination`.
If some folders from `groupOrigin` are moved into `groupDestination` by anyone having access to them (except via the desktop client of the user), the desktop client will delete most of the moved files and folders.

### Steps to reproduce

1. Sync the 3 directories (`groupOrigin`, `groupDestination` and `directShareGroupDestination`)
2. Someone with access using another client moves a folder hierarchy within `groupOrigin` to `groupDestination`
3. The desktop client delete files from this folder hierarchy after it was moved to `groupDestination`

### Expected behavior

No data loss occur and everything is synced as it should (duplicate the content within `groupDestination` and `directShareGroupDestination`

### Which files are affected by this bug

any

### Operating system

Linux

### Which version of the operating system you are running.

Any recent linux distribution

### Package

Appimage

### Nextcloud Server version

27.1.6

### Nextcloud Desktop Client version

3.12.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by mgallien**
Prevent double MOVE instructions for a single file by fixing one place that forgot to track such MOVE instructions

add an automated test to reproduce teh error scenario

add a fix for the wrong behavior

to prevent the issue from coming back also add an assert ensuring a moved file exists

Close #6462

### CODE REVIEW

File: src/libsync/discovery.cpp [hunk 1]
```diff
@@ -1666,6 +1666,9 @@ void ProcessDirectoryJob::processFileFinalize(
         ASSERT(_dirItem && _dirItem->_instruction == CSYNC_INSTRUCTION_RENAME);
         // This is because otherwise subitems are not updated!  (ideally renaming a directory could
         // update the database for all items!  See PropagateDirectory::slotSubJobsFinished)
+        auto adjustedOriginalPath = _discoveryData->adjustRenamedPath(path._original, SyncFileItem::Down);
```
Comment (allexzander) [inline src/libsync/discovery.cpp:1669]: @mgallien is this a leftover?

File: test/testsyncmove.cpp [hunk 2]
```diff
@@ -140,7 +146,22 @@ private slots:
     void testSelectiveSyncMovedFolder()
     {
         // issue #5224
-        FakeFolder fakeFolder{ FileInfo{ QString(), { FileInfo{ QStringLiteral("parentFolder"), { FileInfo{ QStringLiteral("subFolderA"), { { QStringLiteral("fileA.txt"), 400 } } }, FileInfo{ QStringLiteral("subFolderB"), { { QStringLiteral("fileB.txt"), 400 } } } } } } } };
+        FakeFolder fakeFolder{
```
Comment (allexzander) [inline test/testsyncmove.cpp:149]: this change seems unrelevant

File: src/libsync/discovery.cpp (hunk 1 above)
Comment (mgallien) [reply src/libsync/discovery.cpp:1669]: this is needed to avoid having an error due to `[[nodiscard]]`

File: test/testsyncmove.cpp (hunk 2 above)
Comment (mgallien) [reply test/testsyncmove.cpp:149]: I did it for readability purpose
