### PR TITLE
Fix wrong estimated time when doing sync.

### LINKED ISSUE #4891: [Bug]: wrong estimated time shown when doing sync
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Sync progress reported on main dialog can show invalid estimated remaining time.

### Steps to reproduce

1. Start a full sync from a newly setup user account.
2. Open the main dialog
3. See that before downloading any file, the reported remaining time is invalid.

### Expected behavior

Either a valid estimated remaining time is shown or nothing.

### Which files are affected by this bug

not a specific file

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 13.0

### Package

Other

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.5.82

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by allexzander**
Signed-off-by: alex-z <blackslayer4@gmail.com>

This will fix #4891

### CODE REVIEW

**Review by mgallien — APPROVED** [review]

File: src/gui/folderstatusmodel.h [hunk 1]
```diff
@@ -147,6 +147,8 @@ private slots:
     const AccountState *_accountState = nullptr;
     bool _dirty = false; // If the selective sync checkboxes were changed
 
+    bool _isSyncRuningForAwhile = false;
```
Comment (mgallien) [inline src/gui/folderstatusmodel.h:150]: you have a typo
`_isSyncRunningForAwhile`

**Review by mgallien — CHANGES_REQUESTED** [review]

**Review by mgallien — APPROVED** [review]
