### PR TITLE
Notification action buttons and context menu

### LINKED ISSUE #1229: Notifications about app updates are way too frequent
### Expected behaviour

One notification per app per day, *maybe* two.

### Actual behaviour

I think we could all agree that this is a bit too much:

Screenshot from 2019-05-01 20-30-50

I've experienced the same on multiple Linux-based operating systems over the years. This issue usually makes me turn off the notifications all together, but I'm surprised that I could not find an open issue about this behaviour. I do want to be reminded that there's an app update available, just not this frequently.

### Client configuration

* Client version: 2.5.2git
* Operating system: elementary OS 5.0
* OS language: Eng 
* Client package (From Nextcloud or distro) (Linux only): From Nextcloud
* Installation path of client: nextcloud: /usr/bin/nextcloud /usr/lib/x86_64-linux-gnu/nextcloud /usr/share/nextcloud

### LINKED ISSUE #2114: Multiple UI issues for 2FA notifications received in the destop Nextcloud client
When using the Two Factor Authentication plugin ([link](https://github.com/nickv-nextcloud/twofactor_nextcloud_notification)) there are a few UI and user experience issues that could be improved. I was redirected by the author of this plugin to report these here. See my original report: https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/issues/343

### Steps to reproduce
1. Attempt login to Nextcloud
2. Open the Nextcloud client on Windows or MacOS
1. Observe that no Notifications are displayed in Windows or MacOS
3. Go to the Activity tab in the Nextcloud client
1. Observe that Windows or MacOS will not display the notification

### Current behaviour
Multiple problems:
- The Notification on Windows or MacOS is not received until the user opens the Nextcloud client and navigate to the Activity tab
- The "More info" button is non-functional (On my screenshot, it's says "Plus d'informations" which is French for "More info")
- The main path of action (approving or rejecting) is hidden behind the "..." button

### Expected behaviour
- The notification on Windows or MacOS should appear immediately, while the Nextcloud client is active, without having to open it
- The "More info" button has functionality when clicked, or is removed. If this "More info" is meant to say that "there is more info, you should click the "..." button", then this text should not look like a button.
- The main actions (approving or rejecting) should be more prominently displayed, without having to open a sub-menu.

### Client configuration
Client version: Version 2.6.4stable-Win64 (build 20200303)

Operating system: Windows 10 or MacOSX

OS language: Canadian French

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration
Nextcloud version: 17.0.7

### LINKED ISSUE #2624: Nextcloud Desktop client continually notifies the same app update
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I am running Nextcloud Desktop v 3.0.3 on a Mac.  When there is an update for a server component (Collabora Online, in this case), notifications will continually come in.  I expect to get one notification per released version.

### Actual behaviour
Notifications continually come in, approximately once an hour

Screen Shot 2020-11-11 at 7 58 08 AM

For the time being I have disabled server notifications in the client settings.

### Steps to reproduce
1.  Run a local nextcloud server
2.  Install and run Nextcloud Desktop on a Mac
3. When there is an update, expect a notification once an hour

### Client configuration
Client version: 3.0.3

Operating system: Mac

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From Nextcloud or distro) (Linux only): N/A

Installation path of client: Wherever the Mac installer puts it ... ?

### Server configuration
Nextcloud version:20.0.1

Storage backend (external storage): This is running in the lsio docker container

### PR DESCRIPTION
**Pull request by allexzander**
Implemented notification action buttons and context menu for confirm/dismiss and other actions.

Signed-off-by: allexzander <blackslayer4@gmail.com>

Fix #2114
Fix #2624
Fix #1229

### CODE REVIEW

File: src/gui/tray/ActivityListModel.h [hunk 1]
```diff
@@ -74,7 +74,9 @@ class ActivityListModel : public QAbstractListModel
     void removeActivityFromActivityList(int row);
     void removeActivityFromActivityList(Activity activity);
 
-    Q_INVOKABLE void triggerActionAtIndex(int id) const;
+    Q_INVOKABLE void handleClick(int id) const;
+
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.h:78]: nitpick: I'd remove that empty line

File: src/gui/tray/ActivityListModel.h [hunk 2]
```diff
@@ -74,7 +74,9 @@ class ActivityListModel : public QAbstractListModel
     void removeActivityFromActivityList(int row);
     void removeActivityFromActivityList(Activity activity);
 
-    Q_INVOKABLE void triggerActionAtIndex(int id) const;
+    Q_INVOKABLE void handleClick(int id) const;
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.h:77]: I liked the trigger wording better I think... handle is too passive and click is too much tied to how we use it on the GUI (which can change). Old name was slightly misleading though so what about renaming it `triggerDefaultAction`? And I'd also rename `id` into `activityIndex` to be consistent with the new method you introduced.

File: src/gui/tray/ActivityListModel.h [hunk 3]
```diff
@@ -74,7 +74,9 @@ class ActivityListModel : public QAbstractListModel
...
+
+    Q_INVOKABLE void handleAction(int activityIndex, int actionIndex);
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.h:79]: I'd rename this `triggerAction`

File: src/gui/tray/ActivityListModel.cpp [hunk 4]
```diff
@@ -461,6 +465,28 @@ void ActivityListModel::triggerActionAtIndex(int id) const
...
+{
+    if (activityIndex < 0 || activityIndex >= _finalList.size()) {
+        qCWarning(lcActivity) << "Couldn't handle action on activity at index" << activityIndex << "/ final list size:" << _finalList.size();
+        return;
+    }
+
+    const auto actions = _finalList[activityIndex]._links;
+
+    if (actionIndex < 0 || actionIndex >= actions.size()) {
+        qCWarning(lcActivity) << "Couldn't handle action at index" << actionIndex << "/ actions list size:" << actions.size();
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.cpp:478]: As far as logging is concerned, it might be useful to also mention the activityIndex there.

File: src/gui/tray/ActivityListModel.cpp [hunk 5]
```diff
@@ -461,6 +465,28 @@ void ActivityListModel::triggerActionAtIndex(int id) const
...
+        return;
+    }
+
+    if (actions[actionIndex]._verb == "WEB") {
+        QDesktopServices::openUrl(QUrl::fromUserInput(actions[actionIndex]._link));
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.cpp:483]: Same comment, that `fromUserInput` still somehow surprises me

File: src/gui/tray/ActivityListModel.cpp [hunk 6]
```diff
@@ -461,6 +465,28 @@ void ActivityListModel::triggerActionAtIndex(int id) const
...
+        return;
+    }
+
+    emit sendNotificationRequest(_finalList[activityIndex]._accName, actions[actionIndex]._link, actions[actionIndex]._verb, activityIndex);
```
Comment (er-vin) [inline src/gui/tray/ActivityListModel.cpp:487]: For readability reason I'd have an `activity` and an `action` intermediate variables introduced earlier, this would avoid all those `operator[]` calls throughout the method.

File: src/gui/tray/Window.qml [hunk 7]
```diff
@@ -590,11 +584,11 @@ Window {
                     Text {
                         id: activityTextInfo
                         text: (type === "Sync") ? displayPath
-                            : (type === "File") ? subject
-                            : (type === "Notification") ? message
-                            : ""
+                                                : (type === "File") ? subject
```
Comment (er-vin) [inline src/gui/tray/Window.qml:587]: I wouldn't change the indentation there, I find it more readable the way it was before (felt more like pattern matching in a functional language).

File: src/gui/tray/Window.qml [hunk 8]
```diff
@@ -624,56 +618,184 @@ Window {
...
-                    hoverEnabled: true
-                    visible: (path === "") ? false : true
-                    display: AbstractButton.IconOnly
-                    icon.source: "qrc:///client/theme/share.svg"
-                    icon.color: "transparent"
-                    background: Rectangle {
-                        color: parent.hovered ? Style.lightHover : "transparent"
+
+                    function actionButtonIcon(actionIndex) {
+                        if (links[actionIndex]._verb === "WEB" && (objectType === "chat" || objectType === "call")) {
```
Comment (er-vin) [inline src/gui/tray/Window.qml:628]: I'd store the verb in an intermediate variably in the beginning.

Shouldn't that be model.links and model.objectType by the way? Unsure where those are coming from right now.

File: src/gui/tray/Window.qml [hunk 9]
```diff
@@ -624,56 +618,184 @@ Window {
...
                     }
-                    ToolTip.visible: hovered
-                    ToolTip.delay: 1000
-                    ToolTip.text: qsTr("Open Talk")
-                    onClicked: Qt.openUrlExternally(link)
 
-                    Accessible.role: Accessible.Button
-                    Accessible.name: qsTr("Open Talk %1").arg(link)
-                    Accessible.onPressAction: replyButton.clicked()
+                    Button {
```
Comment (er-vin) [inline src/gui/tray/Window.qml:663]: Those buttons feel like they could be somehow created from a Repeater... if you find an obvious way to do this right now go for it. Otherwise let's keep it for a later refactoring once we start splitting proper components out of this giant file.

Comment (allexzander) [reply src/gui/tray/Window.qml:671]: @er-vin Realized that I've altered most of Button's properties, and also I've needed very different behavior for displaying icon/text in the same button. Moved it to a separate file and created a button from scratch with MouseArea.

File: src/gui/tray/ActivityActionButton.qml [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+    // label
+    Text {
+        id: label
+        visible: parent.text !== ""
+        text: parent.text
+        font: parent.font
+        color: parent.hovered ? parent.textColorHovered : parent.textColor
+
+        anchors.centerIn: parent
+        elide: Text.ElideNone
```
Comment (er-vin) [inline src/gui/tray/ActivityActionButton.qml:75]: Are we sure about this? I mean either the width of the button is driven by the text, or the width of the text is driven by the width of the button in which case it should elide.

So far I didn't find a link between those two widths though, so I guess it could overflow?

File: src/gui/tray/ActivityActionButton.qml [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+        }
+    }
+
+    ToolTip {
+        text: parent.tooltipText
+        delay: 1000
+        visible: text != "" && parent.hovered
+    }
+
+    Accessible.role: Accessible.Button
```
Comment (er-vin) [inline src/gui/tray/ActivityActionButton.qml:103]: Those are attached properties, but properties nonetheless, please move them after `signal clicked()`.

File: src/gui/tray/ActivityData.h [hunk 12]
```diff
@@ -27,6 +27,13 @@ namespace OCC {
 
 class ActivityLink
 {
+    Q_GADGET
+
+    Q_PROPERTY(QString label MEMBER _label)
+    Q_PROPERTY(QString link MEMBER _link)
+    Q_PROPERTY(QByteArray verb MEMBER _verb)
+    Q_PROPERTY(bool isPrimary MEMBER _isPrimary)
```
Comment (er-vin) [inline src/gui/tray/ActivityData.h:35]: The convention is to name the property `primary`.

File: src/gui/tray/Window.qml [hunk 13]
```diff
@@ -531,26 +518,30 @@ Window {
             delegate: RowLayout {
                 id: activityItem
 
+                property variant links: model.links
```
Comment (er-vin) [inline src/gui/tray/Window.qml:521]: Make it `readonly`?

File: src/gui/tray/Window.qml [hunk 14]
```diff
@@ -531,26 +518,30 @@ Window {
...
                 height: Style.trayWindowHeaderHeight
                 spacing: 0
 
                 Accessible.role: Accessible.ListItem
                 Accessible.name: path !== "" ? qsTr("Open %1 locally").arg(displayPath)
-                                                    : message
+                                             : message
                 Accessible.onPressAction: activityMouseArea.clicked()
 
+                property int itemIndex: model.index
```
Comment (er-vin) [inline src/gui/tray/Window.qml:532]: Make it `readonly` as well?

File: src/gui/tray/Window.qml [hunk 15]
```diff
@@ -624,56 +616,156 @@ Window {
...
+
+                            textColor: primary ? Style.ncBlue : "black"
+                            textColorHovered: Style.lightHover
+
+                            textBorderColor: Style.ncBlue
+
+                            textBgColor: "transparent"
+                            textBgColorHovered: Style.ncBlue
+
+                            onClicked: activityModel.triggerAction(activityItem.itemIndex, actionIndex)
```
Comment (er-vin) [inline src/gui/tray/Window.qml:659]: I'd put signal handlers at the end of the element.

File: src/gui/tray/Window.qml [hunk 16]
```diff
@@ -624,56 +616,156 @@ Window {
...
+                            target: activityListView
+
+                            onMovementStarted: {
+                                if (moreActionsButtonContextMenu.opened) {
+                                    moreActionsButtonContextMenu.close();
+                                }
+                            }
+                        }
+
+                        Accessible.role: Accessible.Button
```
Comment (er-vin) [inline src/gui/tray/Window.qml:711]: Please move it up with the other attached properties

File: src/gui/tray/Window.qml [hunk 17]
```diff
@@ -624,56 +616,156 @@ Window {
...
+                        }
+                        ToolTip.visible: hovered
+                        ToolTip.delay: 1000
+                        ToolTip.text: qsTr("Show all actions")
+                        onClicked:  moreActionsButtonContextMenu.popup();
+
+                        Connections {
+                            target: trayWindow
+                            onActiveChanged: {
+                                if (!trayWindow.active && moreActionsButtonContextMenu.opened) {
```
Comment (er-vin) [inline src/gui/tray/Window.qml:695]: I wouldn't check on `.opened` and just close. If it's not opened it'll be a noop anyway.

File: src/gui/tray/Window.qml [hunk 18]
```diff
@@ -624,56 +616,156 @@ Window {
...
+                                    moreActionsButtonContextMenu.close();
+                                }
+                            }
+                        }
+
+                        Connections {
+                            target: activityListView
+
+                            onMovementStarted: {
+                                if (moreActionsButtonContextMenu.opened) {
```
Comment (er-vin) [inline src/gui/tray/Window.qml:705]: Same here

File: src/gui/tray/Window.qml [hunk 19]
```diff
@@ -624,56 +616,156 @@ Window {
...
+                        Container {
+                            id: moreActionsButtonContextMenuContainer
+                            visible: moreActionsButtonContextMenu.opened
+                            Menu {
+                                id: moreActionsButtonContextMenu
+                                anchors.centerIn: parent
+
+                                onOpenedChanged: {
+                                    if (opened) {
+                                        moreActionsButtonContextMenuContainer.width = moreActionsButtonContextMenu.width;
```
Comment (er-vin) [inline src/gui/tray/Window.qml:724]: Why isn't this done with bindings?

Also that feels like using `childrenRect` on the moreActionsButtonContextMenuContainer but I'm not sure.
https://doc.qt.io/qt-5/qml-qtquick-item.html#childrenRect-prop

**Comment by er-vin** [comment]
Hm, the automatic rebase failed somehow, you'll have to do it by hand it seems.

File: src/gui/tray/ActivityActionButton.qml [hunk 20]
```diff
@@ -0,0 +1,106 @@
...
+        // padding
+        anchors.topMargin: 10
+        anchors.bottomMargin: 10
+
+        border.color: parent.textBorderColor
+        border.width: parent.labelVisible ? 1 : 0
+
+        color: parent.hovered ? parent.textBgColorHovered : parent.textBgColor
+
+        radius: 25
```
[the remark this answers is not in the document]
Comment (allexzander) [reply src/gui/tray/ActivityActionButton.qml:54]: @er-vin Since I want to achieve "rounded-rectangle" here - 25 is the only value that suits the requirement.

File: src/gui/tray/Window.qml [hunk 21]
```diff
@@ -720,43 +720,45 @@ Window {
...
-                                id: moreActionsButtonContextMenu
-                                anchors.centerIn: parent
+                                    return filteredActions;
+                                }
 
                                 Repeater {
                                     id: moreActionsButtonContextMenuRepeater
-                                    model: moreActionsButtonContextMenuContainer.actionListToContextMenuList(activityItem.links, activityListView.maxActionButtons)
+
+                                    readonly property bool skipTransformModel: activityItem.links.length <= activityListView.maxActionButtons
```
Comment (er-vin) [inline src/gui/tray/Window.qml:753]: Hm, why not have this check done in the function? This way the second parameter could be removed.

File: src/gui/tray/Window.qml [hunk 22]
```diff
@@ -720,43 +720,45 @@ Window {
...
-                                var filteredActions = actionsWithIndices.filter(function(action) {
-                                    return action.primary !== true;
-                                });
+                                        return actionWithIndex;
+                                    });
 
-                                return filteredActions;
-                            }
+                                    // filter 'primary' action out
+                                    var filteredActions = actionsWithIndices.filter(function(action) {
```
Comment (er-vin) [inline src/gui/tray/Window.qml:743]: Just wondering, wouldn't it be better to filter first and map second? Is that possible or the nature of the elements in the input list get in the way?

Comment (allexzander) [reply src/gui/tray/Window.qml:743]: @er-vin Not really. I need an index of the element in the list to use it in 'actionIndex'. Otherwise, if I filter elements first, then I will not have the information to use for 'actionIndex' as the order and the number of the elements would change :(

Actually, I've got an idea. Let me give it a try...

Comment (er-vin) [reply src/gui/tray/Window.qml:743]: > @er-vin Not really. I need an index of the element in the list to use it in 'actionIndex'. Otherwise, if I filter elements first, then I will not have the information to use for 'actionIndex' as the order and the number of the elements would change :(

Oh right...

> Actually, I've got an idea. Let me give it a try...

Well, only if it's easy, otherwise I'd say: don't bother.

Comment (allexzander) [reply src/gui/tray/Window.qml]: @er-vin Actually it happened to be quite easy. Check my last commit with the final improvement.

File: src/gui/tray/Window.qml [hunk 23]
```diff
@@ -725,34 +725,29 @@ Window {
...
+                                    return reducedActionList;
                                 }
 
                                 Repeater {
                                     id: moreActionsButtonContextMenuRepeater
 
-                                    readonly property bool skipTransformModel: activityItem.links.length <= activityListView.maxActionButtons
-
-                                    model: moreActionsButtonContextMenu.actionListToContextMenuList(activityItem.links, skipTransformModel)
+                                    model: moreActionsButtonContextMenu.actionListToContextMenuList(activityItem.links)
```
Comment (er-vin) [inline src/gui/tray/Window.qml:750]: Can't it be `parent.actionListToContextMenuList(activityItem.links)` now?

File: src/gui/tray/Window.qml [hunk 24]
```diff
@@ -725,34 +725,29 @@ Window {
...
                                     // early out with non-altered data
-                                    if (skipTransform === true) {
+                                    if (activityItem.links.length <= activityListView.maxActionButtons) {
                                         return actionList;
                                     }
 
-                                    // add index to every action
-                                    var actionsWithIndices = actionList.map(function(action, index) {
+                                    // add index to every action and filter 'primary' action out
+                                    var reducedActionList = actionList.reduce(function(reduced, action, index) {
```
Comment (er-vin) [inline src/gui/tray/Window.qml:735]: Oh right, a reduce to make it in one pass, good call.

File: src/gui/tray/Window.qml (hunk 23 above)
Comment (allexzander) [reply src/gui/tray/Window.qml:750]: You are really following the path of perfection @er-vin  👍

File: src/gui/tray/ActivityActionButton.qml [hunk 25]
```diff
@@ -0,0 +1,108 @@
...
+    property color textBgColorHovered: Style.lightHover
+
+    // icon background color
+    property color iconBgColor: "transparent"
+    property color iconBgColorHovered: Style.lightHover
+
+    // text border color
+    property color textBorderColor: "transparent"
+
+    property bool hovered: false
```
Comment (er-vin) [inline src/gui/tray/ActivityActionButton.qml:34]: Of course I notice only this late in the review cycle...

This should be a `property alias` to the MouseArea containsMouse property, otherwise it might break property bindings on that hovered property.

File: src/gui/tray/ActivityActionButton.qml [hunk 26]
```diff
@@ -0,0 +1,108 @@
...
+        source: parent.imageSource
+        sourceSize.width: visible ? 32 : 0
+        sourceSize.height: visible ? 32 : 0
+    }
+
+    MouseArea {
+        anchors.fill: parent
+        onClicked: parent.clicked()
+        hoverEnabled: true
+        onHoveredChanged: {
```
Comment (er-vin) [inline src/gui/tray/ActivityActionButton.qml:98]: This signal handler would disappear and this MouseArea get an id.

**Review by er-vin — CHANGES_REQUESTED** [review]
Found a (hopefully) last one. Sorry, I should have spotted it before.

**Review by er-vin — COMMENTED** [review]
Please squash the commits and I think we're good to go.

**Review by camilasan — APPROVED** [review]
