### PR TITLE
Fix #7009: Remove leftover .msi and msi.log after update

### LINKED ISSUE #7009: [Bug]: Updater doesn't clean up installer (.msi)
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud on Windows keeps old installer on path `%appdata%\Nextcloud\Nextcloud-3.13.2-x64.msi`. It has 110MB. By default, you should be deleting it if there is no installation problem. Approximately 100% of your users are very well capable of downloading the installer again should they need to reinstall this client. There is also a useless `msi.log` file having 3MB.

### Steps to reproduce

I think it's from auto-update, but it may very well also be from a normal installation.

### Expected behavior

All temporary files of an installer should be deleted, either immediately, or after some period, but definitely not more than 1 month.

### Which files are affected by this bug

Nextcloud-3.13.2-x64.msi

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

?

### Nextcloud Desktop Client version

3.13.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
There is no data/nextcloud.log
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by chrip**
Fixes #7009

Ensure leftover Windows installers (.msi) and the msiexec log (msi.log) are removed after updates,
both for internal updater flow and for externally performed (manual) installs.

## What I changed
- NSISUpdater::wipeUpdateData() now removes update file and msi.log and logs failures.
- handleStartup() will now call wipeUpdateData() if the update was performed externally.

## How to test
1. Case A (internal updater): simulate a download -> run installer via updater -> restart client -> verify .msi and msi.log are removed.
2. Case B (manual install): download .msi to the config path, run it manually to update, start client -> confirm leftover files are removed.
3. Check logs for messages like "Removed updater file" / "Removed msi log file" or warning messages if removal failed.

## Notes
- This is a Windows-only fix targeted at issue #7009.

Fixes #7009

### CODE REVIEW

File: src/gui/updater/ocupdater.cpp [hunk 1]
```diff
@@ -304,8 +304,21 @@ void NSISUpdater::wipeUpdateData()
...
-        QFile::remove(updateFileName);
+    if (!updateFileName.isEmpty()) {
+        if (QFile::remove(updateFileName)) {
+            qCInfo(lcUpdater) << "Removed updater file:" << updateFileName;
+        } else {
+            qCWarning(lcUpdater) << "Failed to remove updater file:" << updateFileName;
+        }
+    }
+    // Also try to remove the msi log file (created when running msiexec)
+    QString msiLogFileName = cfg.configPath() + "msi.log";
```
Comment (Aiiaiiio) [inline src/gui/updater/ocupdater.cpp]: I would consider using a constant for `msi.log`.

File: src/gui/updater/ocupdater.cpp [hunk 2]
```diff
@@ -304,8 +304,21 @@ void NSISUpdater::wipeUpdateData()
...
+    if (QFile::remove(msiLogFileName)) {
+        qCInfo(lcUpdater) << "Removed msi log file:" << msiLogFileName;
+    } else {
+        qCWarning(lcUpdater) << "Failed to remove msi log file:" << msiLogFileName;
```
Comment (Aiiaiiio) [inline src/gui/updater/ocupdater.cpp]: Would it be good to check whether the current platform is Windows? I wouldn't expect an msi log on any other system.

**Review by Aiiaiiio — APPROVED** [review]
Nice one! Please see my comments as suggestions.

File: src/gui/updater/ocupdater.cpp (hunk 2 above)
Comment (chrip) [reply src/gui/updater/ocupdater.cpp]: Hi @Aiiaiiio, thanks for the suggestion! From what I see, the changes are in NSISUpdater::wipeUpdateData() which is a Windows-specific subclass of OCUpdater. So this code isn’t compiled on other platforms than Windows and no additional platform check should be needed.

File: src/gui/updater/ocupdater.cpp (hunk 1 above)
Comment (chrip) [reply src/gui/updater/ocupdater.cpp]: Thanks, I’ve added a separate commit introducing a constant msiLogFileNameC as suggested.

**Comment by mgallien** [comment]
@chrip do you plan to still work in this PR ?
if yes, could you update us on your plans and eventually make it ready for release

**Comment by chrip** [comment]
The fix I am proposing here is definitely better than the current behavior. In the related issue #7009, there is also the suggestion [“Fetching to %TEMP% would be a better option.”](https://github.com/nextcloud/desktop/issues/7009#issuecomment-3677928587) I have not implemented this improvement and would not change it before the release. As far as I am concerned, this PR is final.

File: src/gui/updater/ocupdater.cpp [hunk 3]
```diff
@@ -304,8 +305,21 @@ void NSISUpdater::wipeUpdateData()
...
-        QFile::remove(updateFileName);
+    if (!updateFileName.isEmpty()) {
+        if (QFile::remove(updateFileName)) {
+            qCInfo(lcUpdater) << "Removed updater file:" << updateFileName;
+        } else {
+            qCWarning(lcUpdater) << "Failed to remove updater file:" << updateFileName;
+        }
+    }
+    // Also try to remove the msi log file (created when running msiexec)
+    QString msiLogFileName = cfg.configPath() + msiLogFileNameC;
```
Comment (mgallien) [inline src/gui/updater/ocupdater.cpp]:
```suggestion
    const auto msiLogFileName = QString{cfg.configPath() + msiLogFileNameC};
```

File: src/gui/updater/ocupdater.cpp [hunk 4]
```diff
@@ -304,8 +305,21 @@ void NSISUpdater::wipeUpdateData()
...
+    if (QFile::remove(msiLogFileName)) {
```
Comment (mgallien) [inline src/gui/updater/ocupdater.cpp]: can you check that the file exists before deleting it ?
that will avoid stray warning about a file not being deleted because it does not exist

**Review by mgallien — CHANGES_REQUESTED** [review]
some small requests for improvements

File: src/gui/updater/ocupdater.cpp (hunk 4 above)
Comment (chrip) [reply src/gui/updater/ocupdater.cpp]: Added check if QFile::exists.

**Review by mgallien — APPROVED** [review]

**Review by nilsding — APPROVED** [review]

**Comment by tgebler** [comment]
Not working in my opinion, 
image

**Comment by chrip** [comment]
@tgebler You are right, thanks for checking and for the screenshot. I can reproduce it, and the cleanup I added doesn't  work as expected.
I will reopened #7009 and will fix it there properly, including the installers that already accumulated.
