### PR TITLE
File Provider Remote Change Discovery Fix

### LINKED ISSUE #8510: [Bug]: macOS VFS not updating folders and files
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Changed File Names from the web and none of the files are changing under the macOS VFS. 

Image

Image

...

### Steps to reproduce

1. Changing multiple folder names under web 
2. Files name not syncing down to mac
...

### Expected behavior

Image

...

### Which files are affected by this bug

all

### Operating system

macOS

### Which version of the operating system you are running.

15.6 (24G84)

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

31.0.7

### Nextcloud Desktop Client version

3.17.0 RC1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by i2h3**
- Changed: The file provider extension no longer polls or listens for server-side changes by itself.
- Changed: The main app, an already existing dependency, is the only process checking for server-side changes.
- Changed: The Enumerator in the file provider extension now also checks the locally materialized items for changed ETags on the server to discover remote changes.
- Removed: RemoteChangeObserver, MockNotifyPushServer and related tests.

Closes #8510.

### CODE REVIEW

**Comment by i2h3** [comment]
This somehow does not work for the push notification method. The main retrieves the current ETag of the root on the server but it apparently is unchanged despite a file being added to the root on the server through web user interface.

**Comment by TheGranadilla** [comment]
Please [i2h3](https://github.com/i2h3) Save us 🤣

File: shell_integration/MacOSX/NextcloudFileProviderKit/Sources/NextcloudFileProviderKit/Enumeration/Enumerator.swift [hunk 1]
```diff
@@ -393,6 +394,131 @@ public final class Enumerator: NSObject, NSFileProviderEnumerator, Sendable {
...
+
+            if readError?.errorCode == 404 {
+                allDeletedMetadatas.append(materializedItem)
+                examinedItemIds.insert(materializedItem.ocId)
+
+                materializedItems.filter {
+                    $0.serverUrl == itemRemoteUrl
+                }.forEach {
+                    allDeletedMetadatas.append($0)
+                    examinedItemIds.insert(materializedItem.ocId)
```
[the remark this answers is not in the document]
Comment (nilsding) [reply shell_integration/MacOSX/NextcloudFileProviderKit/Sources/NextcloudFileProviderKit/Enumeration/Enumerator.swift]: hmm, I now wonder if this filter-loop has ever worked as intended (the very same code was already present in the now-deleted *RemoteChangeObserver* class)

if I read it correctly this seems to only catch the subitems from one given folder, but *not* the subitems of any folders inside it -- and the `examinedItemIds.insert(materializedItem.ocId)` was already done before this loop was entered

File: shell_integration/MacOSX/NextcloudFileProviderKit/Tests/NextcloudFileProviderKitTests/RemoteChangeObserverEtagOptimizationTests.swift [hunk 2]
```diff
@@ -1,176 +0,0 @@
...
-
-    override func setUp() {
-        Realm.Configuration.defaultConfiguration.inMemoryIdentifier = name
-        dbManager = FilesDatabaseManager(account: Self.account, databaseDirectory: makeDatabaseDirectory(), fileProviderDomainIdentifier: NSFileProviderDomainIdentifier("test"), log: FileProviderLogMock())
-        mockRemoteInterface = MockRemoteInterface(account: Self.account, rootItem: MockRemoteItem.rootItem(account: Self.account))
-    }
-
-    func testUnchangedDirectoryShouldNotBeEnumerated() async throws {
-        // This test demonstrates the original issue where multiple working set checks
-        // would repeatedly enumerate the same unchanged folders
```
Comment (nilsding) [inline shell_integration/MacOSX/NextcloudFileProviderKit/Tests/NextcloudFileProviderKitTests/RemoteChangeObserverEtagOptimizationTests.swift:30]: Would it make sense to keep this test (perhaps include it in the *Enumerator* tests)?

apart from the *RemoteChangeObserver*-specific stuff this looks like it's testing the `// OPTIMIZATION:` case that's now inside *Enumerator*

File: src/gui/folderman.h [hunk 3]
```diff
@@ -407,6 +407,11 @@ private slots:
 
     bool _appRestartRequired = false;
 
+#ifdef BUILD_FILE_PROVIDER_MODULE
+    /// Stores last known root ETags per account for File Provider domain signaling
+    QHash<QString, QByteArray> _accountRootETags;
+#endif
```
Comment (nilsding) [inline src/gui/folderman.h]: The account-specific root etag should probably be a new member of the `Account` class -- that way there would no need for the `QHash` in `FolderMan`.

**Comment by Floweb05** [comment]
Hi,
My true appologizes if I'm polluting this with my question... (Huge stress-time over here)
Can you tell if that PR that aim to better detect changement, will fix bugs where :

1. WEB-UI : I delete folder/folder/folder/deleteme     ->    VFS Sync client don't detect deletion and keep deleteme/
2. Mac VFS client : I add a folder "new" in /folder/folder/folder/    ->    VFS client don't detect it and don't sync it to server

From what I understand it's totally that.
You are trying to fix the "recursive" detection, but I may be wrong :S

Thanks a lot everyone.

File: src/gui/folderman.cpp [hunk 4]
```diff
@@ -1042,6 +1045,64 @@ void FolderMan::slotEtagPollTimerTimeout()
...
+
+                    // Signal File Provider about remote changes
+                    Mac::FileProvider::instance()->domainManager()->signalEnumeratorChanged(account.data());
+                } else {
+                    qCDebug(lcFolderMan) << "Root ETag unchanged for account" 
+                                         << account->displayName();
+                }
+            });
+
+        etagJob->start();
```
[the remark this answers is not in the document]
Comment (i2h3) [reply src/gui/folderman.cpp:1100]: This is fine.

File: src/gui/folderman.cpp [hunk 5]
```diff
@@ -1042,6 +1045,64 @@ void FolderMan::slotEtagPollTimerTimeout()
...
+                // Check if ETag has changed
+                const auto lastEtag = _accountRootETags.value(accountId);
+
+                if (lastEtag != etag) {
+                    qCInfo(lcFolderMan) << "Root ETag changed for" << account->displayName()
+                                        << "from" << lastEtag << "to" << etag
+                                        << ", signaling file provider domain.";
+
+                    // Store new ETag
+                    _accountRootETags[accountId] = etag;
```
[the remark this answers is not in the document]
Comment (i2h3) [reply src/gui/folderman.cpp]: This is obsolete due to the refactoring which now stores the latest ETags on the Account object.

File: shell_integration/MacOSX/NextcloudFileProviderKit/Sources/NextcloudFileProviderKit/Enumeration/Enumerator.swift (hunk 1 above)
[the remark this answers is not in the document]
Comment (i2h3) [reply shell_integration/MacOSX/NextcloudFileProviderKit/Sources/NextcloudFileProviderKit/Enumeration/Enumerator.swift]: Indeed, this only matches direct descendants but is not applied recursively which would require comparing the prefix. On the other hand, this might not be an issue on the file provider framework side where removal cascades down to descendants.

The issue Copilot spotted appears to be valid. I change it.

File: src/gui/folderman.h (hunk 3 above)
Comment (i2h3) [reply src/gui/folderman.h]: I updated the code considering this.

File: shell_integration/MacOSX/NextcloudFileProviderKit/Tests/NextcloudFileProviderKitTests/RemoteChangeObserverEtagOptimizationTests.swift (hunk 2 above)
Comment (i2h3) [reply shell_integration/MacOSX/NextcloudFileProviderKit/Tests/NextcloudFileProviderKitTests/RemoteChangeObserverEtagOptimizationTests.swift:30]: I cannot simply adopt it but will try to implement a new test for the same assertions for `Enumerator`.

**Comment by i2h3** [comment]
@Floweb05 I tested the exact cases you described with the changes in this pull request it works as expected.

**Comment by Floweb05** [comment]
> @Floweb05 I tested the exact cases you described with the changes in this pull request it works as expected.

Thank you a lot for this kind update.
I'll test it if I can find the time before release.

File: src/gui/tray/usermodel.cpp [hunk 6]
```diff
@@ -396,6 +419,7 @@ void User::connectPushNotifications() const
 
     connect(_account->account()->pushNotifications(), &PushNotifications::notificationsChanged, this, &User::slotReceivedPushNotification, Qt::UniqueConnection);
     connect(_account->account()->pushNotifications(), &PushNotifications::activitiesChanged, this, &User::slotReceivedPushActivity, Qt::UniqueConnection);
+    connect(_account->account()->pushNotifications(), &PushNotifications::fileIdsChanged, this, &User::slotReceivedPushFileChanges, Qt::UniqueConnection);
```
Comment (nilsding) [inline src/gui/tray/usermodel.cpp:422]: For compatibility with notify_push < 0.4.0 (April 2022, < Nextcloud 24) the signal without the file-ids should be connected as well.

Comment (i2h3) [reply src/gui/tray/usermodel.cpp:422]: Now the auto-merge already happened. I need to split of a new pull request.

**Comment by Floweb05** [comment]
> @Floweb05 I tested the exact cases you described with the changes in this pull request it works as expected.

Deleted folder on Server > No deletion client-side : Unfixed on 33.0.0RC1
See https://github.com/nextcloud/desktop/issues/9425#issuecomment-3934174632

**Comment by juliusvaart** [comment]
We've also still got a issues with this on 33 RC2.

Could it be related to Team-folders / shares?

- MacOS 26.3.1 (25D2128) ARM
- Nextcloud Hub 10 (31.0.13)
- Nextcloud Desktop 33RC2
- Team folders (19.1.17)

Scherm­afbeelding 2026-03-11 om 10 54 31
Scherm­afbeelding 2026-03-11 om 10 54 39

**Comment by i2h3** [comment]
@Floweb05 As explained there, you likely are encountering a different problem which results in the same observation. As @juliusvaart pointed out and I explained in the other issue, there might be an issue how the server advertises changes in certain group folder setups which is a different problem than the client not being abled to reliably learn about any remote changes at all.

**Comment by juliusvaart** [comment]
@i2h3 Should we create an issue in [Groupfolders Github](https://github.com/nextcloud/groupfolders/issues)?

**Comment by i2h3** [comment]
No, please wait. If necessary, I will. See #9602 now, which I opened for this use case. Also @Floweb05 should look at #9602 because I think it is their reported problem.
