### PR TITLE
Fix files not unlocking after lock time expired

### LINKED ISSUE #4956: [Bug]: Desktop Client doesn't unlock file
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

A file which was locked by the server (e.g. a office document opened with Nextcloud Office) doesn't get unlocked again correctly

### Steps to reproduce

1. Create a office document on the client and sync it to the Nextcloud server
2. Open the document on the Nextcloud server with Nextcloud Office
3. The document gets locked in the client:

grafik

4. Cline Nextcloud Office on the server
5. The Server state changes correctly:

grafik

6. But on the client the file stays locked and the righ-click menu only states "Locked by Nextcloud Office, Expire in X minutes"

### Expected behavior

I would expect that a file gets directly (latest after the next sync run / etag check) unlocked if it is no longer locked on the server

### Which files are affected by this bug

-

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 35

### Package

Distro package manager

### Nextcloud Server version

24

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
We have a bug where files are not unlocked after the lock timer expires. This is because there is no indication to the sync engine that a local lock state different to the server lock state needs to be acted on; on top of that, the call to update a file's metadata does not update the lock state of a file.

This PR fixes both of these issues by setting the instruction of an item with a local lock state different to the server to `CSYNC_INSTRUCTION_UPDATE_METADATA`, and also ensures that lock state is updated in the database in the call to `updateLocalMetadata`. It also starts a remote check when the file lock expires.

EDIT: This PR now also schedules sync runs for files that need one to check lock status after the lock times out. Sync runs are minimised by grouping files into buckets of files that need sync runs within 60 seconds of each other, with sync occurring at the latest time possible (i.e. the file in that bucket with the latest sync run request time). Scheduled sync runs are also unscheduled if the file becomes unlocked by the user.

Closes #4956

Signed-off-by: Claudio Cambra <claudio.cambra@gmail.com>

### CODE REVIEW

File: src/libsync/discovery.cpp [hunk 1]
```diff
@@ -373,6 +373,20 @@ void ProcessDirectoryJob::processFile(PathTuple path,
...
+        const auto lockExpirationTime = serverEntry.lockTime + serverEntry.lockTimeout;
+        const auto timeRemaining = QDateTime::currentDateTime().secsTo(QDateTime::fromSecsSinceEpoch(lockExpirationTime));
+        const auto timerInterval = qMax(5ll, timeRemaining);
+
+        qCInfo(lcDisco) << "Will re-check lock status for:" << path._original << "in:" << timerInterval << "seconds.";
+
+        // lockTimeout is in secs, QTimer takes msecs
+        QTimer::singleShot(timerInterval * 1000, this, [this, path]{
+            qCInfo(lcDisco) << "Lock for file:" << path._original << "has expired. Rescanning.";
+            startAsyncServerQuery();
```
Comment (mgallien) [inline src/libsync/discovery.cpp:386]: what do you want to achieve here ?
that line of code will trigger a server query for the state of files at a point were the code is supposed to already have all information about the state of the file
don't you want to trigger a new sync run to apply any eventual changes from server ?

**Review by mgallien — COMMENTED** [review]
would be nice to have a specific automated test to cover explicitly the scenario of the linked github issue

File: src/libsync/discovery.cpp (hunk 1 above)
Comment (claucambra) [reply src/libsync/discovery.cpp:386]: Apologies if I misunderstood the function of this method -- what I want to do is get the lock state from the server instead of applying changes to the lock state of the file locally without checking for changes from the server first. So this timer is intended to schedule a sync run after the lock timer runs out

**Comment by claucambra** [comment]
> would be nice to have a specific automated test to cover explicitly the scenario of the linked github issue

Added local file lock state checking to the existing test for file locking

File: src/libsync/discovery.cpp (hunk 1 above)
Comment (claucambra) [reply src/libsync/discovery.cpp]: Okay, I have changed it to schedule a sync run

File: src/common/syncjournaldb.cpp [hunk 2]
```diff
@@ -1376,6 +1378,13 @@ bool SyncJournalDb::updateLocalMetadata(const QString &filename,
     query->bindValue(2, inode);
     query->bindValue(3, modtime);
     query->bindValue(4, size);
+    query->bindValue(5, lockInfo._locked ? 1 : 0);
+    query->bindValue(6, lockInfo._lockOwnerDisplayName);
+    query->bindValue(7, lockInfo._lockOwnerId);
```
Comment (allexzander) [inline src/common/syncjournaldb.cpp:1383]: @claucambra You have `query->bindValue(7, lockInfo._lockOwnerId);` here, while you also have `lockOwnerId=?8` in the query. Shouldn't this be  `query->bindValue(8, lockInfo._lockOwnerId);`?

File: src/common/syncjournaldb.cpp [hunk 3]
```diff
@@ -1376,6 +1378,13 @@ bool SyncJournalDb::updateLocalMetadata(const QString &filename,
...
+    query->bindValue(8, lockInfo._lockOwnerType);
```
Comment (allexzander) [inline src/common/syncjournaldb.cpp:1384]: @claucambra You have `query->bindValue(8, lockInfo._lockOwnerType);` while you have `lockType=?6` in the query. Shouldn't then `query->bindValue(8, lockInfo._lockOwnerType);` be `query->bindValue(6, lockInfo._lockOwnerType);`?

Comment (claucambra) [reply src/common/syncjournaldb.cpp:1384]: Yeah, damn, I jumbled up the order

Comment (claucambra) [reply src/common/syncjournaldb.cpp]: Fixed now

File: src/common/syncjournaldb.cpp (hunk 2 above)
Comment (claucambra) [reply src/common/syncjournaldb.cpp]: Yeah, apologies -- fixed the order

File: src/libsync/discovery.cpp [hunk 4]
```diff
@@ -516,6 +539,7 @@ void ProcessDirectoryJob::processFileAnalyzeRemoteInfo(
         const bool isVirtualE2EePlaceholder = isDbEntryAnE2EePlaceholder && serverEntry.size >= Constants::e2EeTagSize;
         const qint64 sizeOnServer = isVirtualE2EePlaceholder ? serverEntry.size - Constants::e2EeTagSize : serverEntry.size;
         const bool metaDataSizeNeedsUpdateForE2EeFilePlaceholder = isVirtualE2EePlaceholder && dbEntry._fileSize == serverEntry.size;
+        const bool serverEntryLockedAsBool = serverEntry.locked == SyncFileItem::LockStatus::LockedItem;
```
Comment (allexzander) [inline src/libsync/discovery.cpp:542]: @claucambra I don't think the `AsBool` part is necessary. Could just be `const auto isServerEntryLocked = serverEntry.locked == SyncFileItem::LockStatus::LockedItem;`, then it becomes obvious from the naming.

File: src/libsync/discoveryphase.h [hunk 5]
```diff
@@ -283,6 +283,8 @@ class DiscoveryPhase : public QObject
     // output
     QByteArray _dataFingerprint;
     bool _anotherSyncNeeded = false;
+    QHash<QString, long long> _filesNeedingScheduledSync;
```
Comment (allexzander) [inline src/libsync/discoveryphase.h:286]: @claucambra Wouldn't `qlonglong` work?

File: src/libsync/syncengine.cpp [hunk 6]
```diff
@@ -1116,4 +1131,195 @@ void SyncEngine::slotInsufficientRemoteStorage()
...
+        auto bucketValue = intervalSyncBuckets.value(intervalBucketKey);
+        bucketValue.scheduledSyncTimerSecs = qMax(bucketValue.scheduledSyncTimerSecs, syncScheduledSecs);
+        bucketValue.files.append(file);
+        intervalSyncBuckets.insert(intervalBucketKey, bucketValue);
+    }
+
+    return intervalSyncBuckets;
+}
+
+QSharedPointer<SyncEngine::ScheduledSyncTimer> SyncEngine::nearbyScheduledSyncTimer(const long long scheduledSyncTimerSecs,
```
Comment (allexzander) [inline src/libsync/syncengine.cpp:1242]: @claucambra Once again `qlonglong` should work.

File: src/libsync/syncengine.cpp [hunk 7]
```diff
@@ -1116,4 +1131,195 @@ void SyncEngine::slotInsufficientRemoteStorage()
...
+    }
+
+    for (const auto &file : _discoveryPhase->_filesUnscheduleSync) {
+        const auto fileSyncRunTimer = _filesScheduledForLaterSync.value(file);
+
+        if (fileSyncRunTimer) {
+            fileSyncRunTimer->files.remove(file);
+
+            // Below is only needed for logging
+            const auto currentSecsSinceEpoch = QDateTime::currentSecsSinceEpoch();
```
Comment (allexzander) [inline src/libsync/syncengine.cpp:1314]: @claucambra You can use `currentMSecsSinceEpoch` and avoid division later.

File: src/libsync/discovery.cpp (hunk 4 above)
Comment (claucambra) [reply src/libsync/discovery.cpp]: This is cleaner, thanks, changed

File: src/libsync/discoveryphase.h (hunk 5 above)
Comment (claucambra) [reply src/libsync/discoveryphase.h:286]: Since the method returns a `qint64` I will use that, though they are all just aliases of `long long`

File: src/libsync/syncengine.cpp (hunk 7 above)
Comment (claucambra) [reply src/libsync/syncengine.cpp]: Yes, changed to msecs

File: src/libsync/discoveryphase.h (hunk 5 above)
Comment (claucambra) [reply src/libsync/discoveryphase.h:286]: Sure :)

File: src/libsync/discovery.cpp [hunk 8]
```diff
@@ -551,6 +575,8 @@ void ProcessDirectoryJob::processFileAnalyzeRemoteInfo(
             }
             item->_instruction = CSYNC_INSTRUCTION_UPDATE_METADATA;
             item->_direction = SyncFileItem::Down;
+        } else if(isServerEntryLocked != dbEntry._lockstate._locked) {
```
Comment (allexzander) [inline src/libsync/discovery.cpp:578]: @claucambra Are you sure this will not change sync behavior? Like, if the file has been also changed on the server, with this `else if`, we will never go into `else's` logic...

Comment (allexzander) [reply src/libsync/discovery.cpp:578]: @claucambra My assumption could be wrong, so, just to be more precise, what I want is for us to make sure we only need to update metadata and nothing else besides lock state change has happened with the file.

Comment (claucambra) [reply src/libsync/discovery.cpp]: I am not sure, so to be safe I have moved this check onto a lambda that gets called in the final and the outside branch of the if

**Review by allexzander — APPROVED** [review]
