### PR TITLE
Fix folder wizard warning color for local path in dark mode

### LINKED ISSUE #5852: [Bug]: Sync warning is unreadable on Mac under dark mode
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When creating a sync folder separately from the root sync and the destination is in the root, a warning comes that says something like:

`Warning: You are already syncing /, which is a parent folder of /ChildFolder.`

Under Mac, with Dark Mode enabled, the warning is unreadable due to contrast issues:

image

### Steps to reproduce

1. Open the Nextcloud Desktop Settings
2. Click Add Folder Sync Connection
3. Select a local folder and click Continue
4. Select a destination folder

### Expected behavior

The warning should have either a different background color or text color to ensure a readable contrast ratio.

### Which files are affected by this bug

N/A

### Operating system

Mac OS

### Which version of the operating system you are running.

13.4.1

### Package

Other

### Nextcloud Server version

27.0.0

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
N/A
```

### Additional info

In addition to this issue, I don't believe the warning should be showing at all in my use case, as I have deselected the child folder from the root sync, so it is not really syncing twice when this folder configuration is being created.

### PR DESCRIPTION
**Pull request by claucambra**
We had originally fixed this for the remote path, but not for the local path. Without this fix the warning is unreadable

Fixes #5852

### CODE REVIEW

File: src/gui/folderwizard.cpp [hunk 1]
```diff
@@ -523,6 +526,31 @@ void FolderWizardRemotePath::showWarn(const QString &msg) const
...
+    default:
+        break;
+    }
+
+    FormatWarningsWizardPage::changeEvent(e);
+}
+
+void FolderWizardRemotePath::changeStyle()
+{
+    const auto warnYellow = Theme::instance()->darkMode() ? QColor(63, 63, 0) : QColor(255, 255, 192);
```
Comment (allexzander) [inline src/gui/folderwizard.cpp:547]: @claucambra the body seems identical to `FolderWizardLocalPath::changeStyle()`, could you aply DRY? If not possible, at least move colors to `constexpr`

**Review by allexzander — CHANGES_REQUESTED** [review]

File: src/gui/folderwizard.cpp (hunk 1 above)
Comment (claucambra) [reply src/gui/folderwizard.cpp]: I moved the palette generation to a shared function in anonymous namespace, unfortunately can't move everything out as the `_ui` types are different

**Review by allexzander — APPROVED** [review]

**Comment by allexzander** [comment]
@claucambra Kindly squash your commits
