### PR TITLE
Display error message when creating a link share with compromised password.

### LINKED ISSUE #4136: Properly display password requirements error message when creating a share with enforced password
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
A password requirements message must be displayed when attempting to create a share with a password enforced.

### Actual behaviour
A password prompt pops up again and again when the password strength is too low, without providing a clear explanation to the user.

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

### PR DESCRIPTION
**Pull request by allexzander**
Signed-off-by: alex-z <blackslayer4@gmail.com>

error_message_in_dialog
This will fix #4136

### CODE REVIEW

**Review by claucambra — APPROVED** [review]

**Comment by camilasan** [comment]
I think we need to involve @jancborchardt :)

File: src/gui/passwordinputdialog.cpp [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    ui->labelErrorMessage->setVisible(!error.isEmpty());
+
+    setWindowFlags(windowFlags() & ~Qt::WindowContextHelpButtonHint);
+}
+
+PasswordInputDialog::~PasswordInputDialog()
+{
+    delete ui;
+}
+QString PasswordInputDialog::password() const
```
Comment (camilasan) [inline src/gui/passwordinputdialog.cpp:39]: new line before password()?

**Comment by jancborchardt** [comment]
Looks ok for this one, but maybe it’s a bit nicer to read if we don’t use red color for the text but rather our grey/maxcontrast color: https://docs.nextcloud.com/server/latest/developer_manual/design/foundations.html#text-color

**Comment by allexzander** [comment]
> maxcontrast

@jancborchardt 
image
Is that what you mean?

**Comment by jancborchardt** [comment]
> > maxcontrast
> 
> @jancborchardt image Is that what you mean?

Exactly, looks much better! :) :+1:

File: src/gui/passwordinputdialog.h [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    Q_OBJECT
+
+public:
+    explicit PasswordInputDialog(const QString &description, const QString &error, QWidget *parent = nullptr);
+    ~PasswordInputDialog() override;
+
+    QString password() const;
+
+private:
+    Ui::PasswordInputDialog *ui;
```
Comment (mgallien) [inline src/gui/passwordinputdialog.h:36]: can you replace it with a smart pointer (most probably `std::unique_ptr`) ?

**Review by mgallien — CHANGES_REQUESTED** [review]
a minor change inspired by the automated checks

**Comment by allexzander** [comment]
> a minor change inspired by the automated checks

@mgallien Fixed!

**Review by jancborchardt — APPROVED** [review]
:+1: design-wise :)

**Review by mgallien — APPROVED** [review]

**Review by camilasan — APPROVED** [review]

**Comment by mgallien** [comment]
@alex can you squash the commits before merging ?
