### PR TITLE
Close call notifications when the call has been joined by the user, or the call has ended

### LINKED ISSUE #4497: [Bug]: Call notification is not fading when the call was accepted somewhere else
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The call popup does not disappear when the notification is not there anymore

See green: I'm in the very same call
See red: there is no call notification in the API anymore
Bildschirmfoto vom 2022-05-06 11-02-38

### Steps to reproduce

1. Receive a call notification
2. Do not interact with it
3. Open the browser and delete the notification or accept the call in the browser directly or ...

### Expected behavior

Call notification is gone

### Which files are affected by this bug

?

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04

### Package

Distro package manager

### Nextcloud Server version

24.0.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by claucambra**
This PR adds a `CallStateChecker` that polls the state of the call being notified, much like the Talk iOS app, and stops the call notification if:

- The call has been joined by the user
- The call has been ended (i.e. all users have left the all)
- The notification timer has run out (60 seconds)

Fixes #4497

### CODE REVIEW

File: src/gui/callstatechecker.cpp [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+    _notificationTimer.start();
+    _statusCheckTimer.start();
+}
+
+void CallStateChecker::stopChecking()
+{
+    qCInfo(lcCallStateChecker, "Stopping checking of call state.");
+    _notificationTimer.stop();
+    _statusCheckTimer.stop();
+    _stateCheckJob.clear();
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:81]: not sure if this is really useful ?

File: src/gui/callstatechecker.cpp [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+{
+    qCInfo(lcCallStateChecker, "Notification timer elapsed, stopping call checking");
+    stopChecking();
+    Q_EMIT notificationTimerElapsed();
+}
+
+void CallStateChecker::slotStatusCheckTimerElapsed()
+{
+    // Don't run check if another check is still ongoing
+    if (!_stateCheckJob.isNull()) {
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:101]: I find `if (_stateCheckJob) {` to be easier to read

File: src/gui/callstatechecker.cpp [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+}
+
+bool CallStateChecker::isAccountServerVersion22OrLater() const
+{
+    if(!_accountState || !_accountState->account()) {
+        return false;
+    }
+
+    const auto accountNcVersion = _accountState->account()->serverVersionInt();
+    const auto ncVersion22 = OCC::Account::makeServerVersion(22, 0, 0);
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:115]: could you try to make this a constexpr ?
looks like a good candidate

File: src/gui/callstatechecker.cpp [hunk 4]
```diff
@@ -0,0 +1,181 @@
...
+        Q_EMIT callAbandoned();
+        stopChecking();
+        return;
+    }
+
+    for (const auto &participant : participantsJsonArray) {
+        const auto participantDataObject = participant.toObject();
+        const auto participantId = isAccountServerVersion22OrLater() ? participantDataObject.value("actorId").toString() : participantDataObject.value("userId").toString();
+
+        qDebug() << _accountState->account()->davUser();
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:171]: left from debug or would you like to keep it ?

File: src/gui/callstatechecker.cpp (hunk 3 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp:115]: `non constexpr function 'makeServerVersion' cannot be used in a constant expression` :(

File: src/gui/callstatechecker.cpp (hunk 1 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp:81]: We use the null-ness of the pointer to know whether we should run a new check or not, so here we are clearing it early (before check is complete) to know we can run another check immediately

File: src/gui/tray/notificationhandler.cpp [hunk 5]
```diff
@@ -108,6 +108,8 @@ void ServerNotificationHandler::slotNotificationsReceived(const QJsonDocument &j
         // 1. server == 24 & has Talk: object_type is chat/call/room & object_id contains conversationToken/messageId
         // 2. server < 24 & has Talk: object_type is chat/call/room & object_id contains _only_ conversationToken
         if (a._objectType == "chat" || a._objectType == "call" || a._objectType == "room") {
+            qCDebug(lcServerNotification) << "Received talk notification: " << json;
```
[the remark this answers is not in the document]
Comment (claucambra) [reply src/gui/tray/notificationhandler.cpp]: No, I removed it

File: src/gui/callstatechecker.cpp [hunk 6]
```diff
@@ -0,0 +1,181 @@
...
+    setup();
+}
+
+void CallStateChecker::setup()
+{
+    _notificationTimer.setSingleShot(true);
+    _notificationTimer.setInterval(60 * 1000);
+    connect(&_notificationTimer, &QTimer::timeout, this, &CallStateChecker::slotNotificationTimerElapsed);
+
+    _statusCheckTimer.setInterval(1000);
```
[the remark this answers is not in the document]
Comment (claucambra) [reply src/gui/callstatechecker.cpp]: Yeah, I changed it to 2 seconds now

File: src/gui/callstatechecker.cpp (hunk 2 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp]: Changed it to your suggestion

File: src/gui/callstatechecker.cpp (hunk 4 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp]: Nope, removed it

File: src/gui/callstatechecker.cpp (hunk 3 above)
Comment (mgallien) [reply src/gui/callstatechecker.cpp:114]: but cannot you make `OCC::Account::makeServerVersion` a `constexpr` ?

File: src/gui/callstatechecker.cpp [hunk 7]
```diff
@@ -0,0 +1,181 @@
...
+CallStateChecker::CallStateChecker(QObject *parent)
+    : QObject(parent)
+{
+    setup();
+}
+
+void CallStateChecker::setup()
+{
+    _notificationTimer.setSingleShot(true);
+    _notificationTimer.setInterval(60 * 1000);
```
[the remark this answers is not in the document]
Comment (mgallien) [reply src/gui/callstatechecker.cpp:37]: but how do other Talk clients handle this timeout ?

[the remark this answers is not in the document]
Comment (claucambra) [reply src/gui/callstatechecker.cpp:37]: iOS Talk has a [max ringing time of 45 seconds](https://github.com/nextcloud/talk-ios/blob/529bdc88341518569a7a470b6ca7a535d6e70cdf/NextcloudTalk/CallKitManager.m#L43)

File: src/gui/callstatechecker.cpp (hunk 3 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp:114]: In trying to do this I get this error:

```
auto components = serverVersion().split('.'); 

[account.cpp:654:10: Variable of non-literal type 'QStringList' cannot be defined in a constexpr function
qstringlist.h:111:7: 'QStringList' is not literal because it is not an aggregate and has no constexpr constructors other than copy or move constructors]
```

I there some other way we can get the major, min, micro numbers?

Comment (mgallien) [reply src/gui/callstatechecker.cpp:114]: let's maybe close this but I was talking about using this definition of `OCC::Account::makeServerVersion`
```
    static constexpr int makeServerVersion(int majorVersion, int minorVersion, int patchVersion)
    {
        return (majorVersion << 16) + (minorVersion << 8) + patchVersion;
    }
```
should then allow to get those constant versions be real constant

Comment (mgallien) [reply src/gui/callstatechecker.cpp:114]: but that is not really important to fix now
would be nice to have

File: src/gui/callstatechecker.h [hunk 8]
```diff
@@ -0,0 +1,70 @@
...
+    Q_PROPERTY(AccountState* accountState READ accountState WRITE setAccountState NOTIFY accountStateChanged)
+
+public:
+    explicit CallStateChecker(QObject *parent = nullptr);
+
+    QString token() const;
+    void setToken(const QString &token);
+
+    AccountState* accountState() const;
+    void setAccountState(AccountState *accountState);
```
Comment (mgallien) [inline src/gui/callstatechecker.h:38]: make it a slot

File: src/gui/callstatechecker.h [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+{
+    Q_OBJECT
+    Q_PROPERTY(QString token READ token WRITE setToken NOTIFY tokenChanged)
+    Q_PROPERTY(AccountState* accountState READ accountState WRITE setAccountState NOTIFY accountStateChanged)
+
+public:
+    explicit CallStateChecker(QObject *parent = nullptr);
+
+    QString token() const;
+    void setToken(const QString &token);
```
Comment (mgallien) [inline src/gui/callstatechecker.h:35]: make it a slot

File: src/gui/callstatechecker.h [hunk 10]
```diff
@@ -0,0 +1,70 @@
...
+    AccountState* accountState() const;
+    void setAccountState(AccountState *accountState);
+
+signals:
+    void tokenChanged();
+    void accountStateChanged();
+
+    void callJoined();
+    void callAbandoned();
+    void notificationTimerElapsed();
```
Comment (mgallien) [inline src/gui/callstatechecker.h:46]: do we really need the three signals (especially as their have the same effect in qml code) ?
maybe they could be replace by `notificationFinished` or something similar ?

File: src/gui/callstatechecker.h [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+
+public slots:
+    void startChecking();
+    void stopChecking();
```
Comment (mgallien) [inline src/gui/callstatechecker.h:50]: should we not better use a property named `checking` that would be set to `true` when we want the checking to occur ?
sounds easier to then set a binding on the qml side

File: src/gui/callstatechecker.h [hunk 12]
```diff
@@ -0,0 +1,70 @@
...
+    void slotNotificationTimerElapsed();
+    void slotCallStateReceived(const QJsonDocument &json, int statusCode);
+    void reset();
+
+private:
+    void setup();
+    void startCallStateCheck();
+    bool isAccountServerVersion22OrLater() const;
+
+    AccountState *_accountState;
```
Comment (mgallien) [inline src/gui/callstatechecker.h:63]: can you initialize it to a `nullptr` ?

File: src/gui/callstatechecker.cpp [hunk 13]
```diff
@@ -0,0 +1,179 @@
...
+void CallStateChecker::setAccountState(AccountState *state)
+{
+    _accountState = state;
+    Q_EMIT accountStateChanged();
+    reset();
+}
+
+void CallStateChecker::startChecking()
+{
+    qCInfo(lcCallStateChecker, "Starting to check state of call.");
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:70]: maybe we could also add the `_token` in case we would need to analyze any future issue

File: src/gui/callstatechecker.cpp [hunk 14]
```diff
@@ -0,0 +1,179 @@
...
+void CallStateChecker::reset()
+{
+    qCInfo(lcCallStateChecker, "Resetting call check");
+    stopChecking();
+    startChecking();
+}
+
+void CallStateChecker::slotNotificationTimerElapsed()
+{
+    qCInfo(lcCallStateChecker, "Notification timer elapsed, stopping call checking");
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:92]: maybe we could also add the `_token` in case we would need to analyze any future issue

File: src/gui/callstatechecker.cpp [hunk 15]
```diff
@@ -0,0 +1,179 @@
...
+    if (!(_accountState && _accountState->isConnected() &&
+          _accountState->account() && _accountState->account()->credentials() &&
+          _accountState->account()->credentials()->ready())) {
+        qCInfo(lcCallStateChecker, "Could not connect, can't check call state.");
+        return;
+    }
+
+    // Check for token
+    if(_token.isEmpty()) {
+        qCInfo(lcCallStateChecker, "No call token set, can't check without it.");
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:131]: you are missing a `return` on the next line

File: src/gui/callstatechecker.cpp [hunk 16]
```diff
@@ -0,0 +1,179 @@
...
+{
+    if (statusCode != successStatusCode) {
+        qCInfo(lcCallStateChecker) << "Failed to retrieve call state data. Server returned status code: " << statusCode;
+        return;
+    }
+
+    qCInfo(lcCallStateChecker, "Successfully retrieved call state data.");
+
+    const auto participantsJsonArray = json.object().value("ocs").toObject().value("data").toArray();
+    qCDebug(lcCallStateChecker) << participantsJsonArray;
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:157]: do we really need to keep this one ?

File: src/gui/callstatechecker.cpp [hunk 17]
```diff
@@ -0,0 +1,179 @@
...
+}
+
+void CallStateChecker::slotCallStateReceived(const QJsonDocument &json, int statusCode)
+{
+    if (statusCode != successStatusCode) {
+        qCInfo(lcCallStateChecker) << "Failed to retrieve call state data. Server returned status code: " << statusCode;
+        return;
+    }
+
+    qCInfo(lcCallStateChecker, "Successfully retrieved call state data.");
```
Comment (mgallien) [inline src/gui/callstatechecker.cpp:154]: do we really need to keep this one ?

File: src/gui/callstatechecker.h (hunk 8 above)
Comment (claucambra) [reply src/gui/callstatechecker.h]: Done

File: src/gui/callstatechecker.h (hunk 9 above)
Comment (claucambra) [reply src/gui/callstatechecker.h]: Done

File: src/gui/callstatechecker.h (hunk 10 above)
Comment (claucambra) [reply src/gui/callstatechecker.h]: Replaced them with one `stopNotifying` signal

File: src/gui/callstatechecker.h (hunk 11 above)
Comment (claucambra) [reply src/gui/callstatechecker.h]: I replaced `startChecking` and `stopChecking` with a property

File: src/gui/callstatechecker.h (hunk 12 above)
Comment (claucambra) [reply src/gui/callstatechecker.h]: Done

File: src/gui/callstatechecker.cpp (hunk 16 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp]: Nope, removed

File: src/gui/callstatechecker.cpp (hunk 17 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp]: No, removed it

File: src/gui/callstatechecker.cpp (hunk 3 above)
Comment (claucambra) [reply src/gui/callstatechecker.cpp]: I was looking at the wrong method 🤦‍♂️ I was able to make it a constexpr now

**Review by mgallien — COMMENTED** [review]
please squash commits and I then approve (according to our review procedure)
this time I do not forget

**Review by allexzander — APPROVED** [review]

**Review by mgallien — APPROVED** [review]

File: src/gui/callstatechecker.cpp [hunk 18]
```diff
@@ -0,0 +1,184 @@
...
+    setup();
+}
+
+void CallStateChecker::setup()
+{
+    _notificationTimer.setSingleShot(true);
+    _notificationTimer.setInterval(60 * 1000);
+    connect(&_notificationTimer, &QTimer::timeout, this, &CallStateChecker::slotNotificationTimerElapsed);
+
+    _statusCheckTimer.setInterval(2 * 1000);
```
Comment (nickvergessen) [inline src/gui/callstatechecker.cpp:40]: Since this basically DDoSes the server, you might use 5 secs as well like the mobile clients do?
https://github.com/nextcloud/talk-ios/blob/529bdc88341518569a7a470b6ca7a535d6e70cdf/NextcloudTalk/CallKitManager.m#L44

But also in case the user joined, you should receive a notify_push about the call notification being deleted.
Listening to that and then removing also the popup+sound would have been good enough from my POV, but now you made the effort already so it's okay to keep.
