### PR TITLE
Set VFS PinState to Excluded for ignored files.

### LINKED ISSUE #5524: [Bug]: ignored files always show state 'sync pending'
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

ignored files always show state 'sync pending'

### Steps to reproduce

1. have some files that are ignored from sync per configuration.
grafik

2. look at some of those files in Windows Explorer:
grafik

3. the files show 'sync pending' while hovering and in status line. The status icon is also suggesting 'sync pending'.

### Expected behavior

File status and icon should somehow show that this file is exempted from sync.
Icon could be corresponding to the tray window
(
grafik
)

### Which files are affected by this bug

all files that are ignored by configuration

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

25.0.4

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #5594: [Bug]: Nextcloud VFS on Windows always displays "syncing" icon for .lnk files
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

.lnk files always have their status icon displayed as "syncing" when in VFS mode on Windows

### Steps to reproduce

1. Sync a folder with VFS mode and have .lnk files synced to the server
2. Observer the status for every other file in a local folder in Windows Explorer and notice the status icon can change from "online only" to "syncing" and so on
3. For .lnk files the status is always "syncing"(refreshing icon)

### Expected behavior

.lnk file needs to have a correct status

### Which files are affected by this bug

.lnk files

### Operating system

Windows

### Which version of the operating system you are running.

All

### Package

Other

### Nextcloud Server version

all

### Nextcloud Desktop Client version

3.8.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

_No response_

### Additional info

_No response_

### LINKED ISSUE #5825: [Bug]: Virtual files - Status icons from shortcuts don't get updated
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The status icon of shortcuts and .lnk files (also shortcuts) always shows "sync in progress". The synchronization itself works without any problems. It also doesn't matter if the shortcuts are synced to the server or from the server. The problem only occurs when virtual files are enabled.

The same happens to files on the exclude list.

### Steps to reproduce

1. Setup Nextcloud with virtual files
2. Put some shortcuts or .lnk-files in the local folder
3. The files get synced, but the icons stay at "sync in progress"

### Expected behavior

The file should get a green tick or cloud icon.

### Which files are affected by this bug

Neues Textdokument.txt - Verknüpfung

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Enterprise

### Package

Other

### Nextcloud Server version

26.0.2

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
there are no related errors on the server
```

### Additional info

lnk

[Debug archive](https://github.com/nextcloud/desktop/files/11797411/log.zip)

### PR DESCRIPTION
**Pull request by m7913d**
Setting PinState to Excluded ensures the syncing icon is not shown for ignored items. 
If the PinState is not set to Excluded, also all parent directories are shown as being synced, which is very inconvenient for the end user as it seems that some folder are never fully synced by Nextcloud which isn't the case. 
As long as .lnk files are not converted to placeholder files, also set them to Excluded to hide the syncing icon.

Closes #5524
Closes #5594
Closes #5825

### CODE REVIEW

**Comment by m7913d** [comment]
1. Note that this implementation generates many warnings "Couldn't find pin state for regular non-placeholder file" when calling `VfsCfApi::pinStateLocal` inside `Folder::slotWatchedPathChanged` on non placeholder files. Not sure if this warning is relevant. Note that we could set the PinState on non placeholder files, but querying the PinState seems to fail. OneDrive seems to do the same.

2. When setting the PinState to Excluded no sync icon is shown for that file. However, on OneDrive a special 'excluded' icon is shown:
afbeelding
I'm not sure if and how we can set such an icon too, but showing no icon is at least much better than showing the syncing icon indefinitely.

**Comment by m7913d** [comment]
@mgallien Is this PR eligible to be merged? Should someone else review this PR? Please do not hesitate to contact me if you need more information or something should be changed prior to being merged.

**Comment by m7913d** [comment]
Note that the "Windows Build and Test / Build" workflow fails due to external changes. PR #5874 provides a fix for this failed workflow. Please rerun the check after that PR is approved.

**Comment by m7913d** [comment]
Closes #5825

File: src/libsync/vfs/cfapi/vfs_cfapi.h [hunk 1]
```diff
@@ -76,6 +76,9 @@ public slots:
     void onHydrationJobFinished(HydrationJob *job);
     HydrationJob *findHydrationJob(const QString &requestId) const;
 
+    bool setPinStateLocal(const QString &localPath, PinState state);
+    Optional<PinState> pinStateLocal(const QString &localPath);
```
Comment (mgallien) [inline src/libsync/vfs/cfapi/vfs_cfapi.h:80]:
```suggestion
    [[nodiscard]] Optional<PinState> pinStateLocal(const QString &localPath) const;
```

**Review by mgallien — CHANGES_REQUESTED** [review]
thanks a lot

File: src/libsync/vfs/cfapi/vfs_cfapi.cpp [hunk 2]
```diff
@@ -304,6 +313,11 @@ Optional<PinState> VfsCfApi::pinState(const QString &folderPath)
 {
     const auto localPath = QDir::toNativeSeparators(params().filesystemPath + folderPath);
 
+    return pinStateLocal(localPath);
+}
+
+Optional<PinState> VfsCfApi::pinStateLocal(const QString &localPath)
```
Comment (m7913d) [inline src/libsync/vfs/cfapi/vfs_cfapi.cpp:319]:
```suggestion
Optional<PinState> VfsCfApi::pinStateLocal(const QString &localPath) const
```

File: src/gui/folderwatcher.cpp [hunk 3]
```diff
@@ -68,18 +68,7 @@ void FolderWatcher::init(const QString &root)
 
 bool FolderWatcher::pathIsIgnored(const QString &path)
```
Comment (m7913d) [inline src/gui/folderwatcher.cpp:69]:
```suggestion
bool FolderWatcher::pathIsIgnored(const QString &path) const
```

File: src/gui/folder.cpp [hunk 4]
```diff
@@ -806,6 +821,20 @@ void Folder::removeFromSettings() const
     settings->remove(FolderMan::escapeAlias(_definition.alias));
 }
 
+bool Folder::pathIsIgnored(const QString &path)
```
Comment (m7913d) [inline src/gui/folder.cpp:824]:
```suggestion
bool Folder::pathIsIgnored(const QString &path) const
```

File: src/gui/folder.cpp [hunk 5]
```diff
@@ -561,6 +561,21 @@ void Folder::slotWatchedPathChanged(const QString &path, ChangeReason reason)
 
     auto relativePath = path.midRef(this->path().size());
 
+    if (pathIsIgnored(path)) {
+        auto pinState = _vfs->pinState(relativePath.toString());
```
Comment (mgallien) [inline src/gui/folder.cpp:565]:
```suggestion
        const auto pinState = _vfs->pinState(relativePath.toString());
```

File: src/gui/folder.cpp [hunk 6]
```diff
@@ -561,6 +561,21 @@ void Folder::slotWatchedPathChanged(const QString &path, ChangeReason reason)
...
+        if (!pinState || *pinState != PinState::Excluded) {
+            if (!_vfs->setPinState(relativePath.toString(), PinState::Excluded))
+                qCWarning(lcFolder) << "Could not set pin state of" << relativePath << "to excluded";
+        }
+        return;
+    } else {
+        auto pinState = _vfs->pinState(relativePath.toString());
```
Comment (mgallien) [inline src/gui/folder.cpp:572]:
```suggestion
        const auto pinState = _vfs->pinState(relativePath.toString());
```

File: src/gui/folder.cpp [hunk 7]
```diff
@@ -806,6 +821,21 @@ void Folder::removeFromSettings() const
...
 
+bool Folder::pathIsIgnored(const QString &path) const
+{
+    if (path.isEmpty()) {
+        return true;
+    }
+
+#ifndef OWNCLOUD_TEST
+    if (isFileExcludedAbsolute(path) && !Utility::isConflictFile(path)) {
+        qCDebug(lcFolderWatcher) << "* Ignoring file" << path;
```
Comment (mgallien) [inline src/gui/folder.cpp:832]:
```suggestion
        qCDebug(lcFolder) << "* Ignoring file" << path;
```

**Review by mgallien — CHANGES_REQUESTED** [review]

**Comment by mgallien** [comment]
@m7913d could you squash your commits as I do not think it is needed to keep 3 commits ?
then I approve and make sure this is merged
thanks again for your contribution

**Comment by m7913d** [comment]
@mgallien Commits are squashed.

**Review by mgallien — APPROVED** [review]

**Review by claucambra — APPROVED** [review]

**Comment by m7913d** [comment]
@mgallien @claucambra As mentioned in my second comment, this PR generates a lot of warnings "Couldn't find pin state for regular non-placeholder file". Is this ok for you? Should we remove the warning, lower the warning to a debug/info message or use another function to check if the file has a pin state?

**Comment by mgallien** [comment]
> @mgallien @claucambra As mentioned in my second comment, this PR generates a lot of warnings "Couldn't find pin state for regular non-placeholder file". Is this ok for you? Should we remove the warning, lower the warning to a debug/info message or use another function to check if the file has a pin state?

@m7913d I think (but I cannot check) that this warning dates from the early stages of this code
I would go with debug level as I would not expect this warning to really be useful now
thanks for pinging us about this as I had overlooked your question

File: src/libsync/vfs/cfapi/vfs_cfapi.cpp [hunk 8]
```diff
@@ -224,12 +224,16 @@ Result<void, QString> VfsCfApi::dehydratePlaceholder(const SyncFileItem &item)
 
 Result<Vfs::ConvertToPlaceholderResult, QString> VfsCfApi::convertToPlaceholder(const QString &filename, const SyncFileItem &item, const QString &replacesFile)
 {
+    const auto localPath = QDir::toNativeSeparators(filename);
+
     if (item._type != ItemTypeDirectory && OCC::FileSystem::isLnkFile(filename)) {
         qCInfo(lcCfApi) << "File \"" << filename << "\" is a Windows shortcut. Not converting it to a placeholder.";
+        const auto pinState = pinStateLocal(localPath);
+        if (!pinState || *pinState != PinState::Excluded)
+            setPinStateLocal(localPath, PinState::Excluded);
```
Comment (mgallien) [inline src/libsync/vfs/cfapi/vfs_cfapi.cpp:233]:
```suggestion
        if (!pinState || *pinState != PinState::Excluded) {
            setPinStateLocal(localPath, PinState::Excluded);
        }
```

**Review by mgallien — CHANGES_REQUESTED** [review]
see my comment
somehow missed that earlier, sorry

**Review by mgallien — APPROVED** [review]
