### PR TITLE
FinderSync Crash due to Socket Reading (stable-33.0)

### LINKED ISSUE #9581: [Bug]: Recurring pop-up with "FinderSyncExt quit unexpectedly"
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Potential follow-up of #5193.

Many times throughout the day I get the following error pop-up:
Image
with the following error report:
[2026-03-09_nextcloud-finder-crash.log](https://github.com/user-attachments/files/25848303/2026-03-09_nextcloud-finder-crash.log)

Debug logs:
[nextcloud-debug.zip](https://github.com/user-attachments/files/25848409/nextcloud-debug.zip)

### Steps to reproduce

Unknown. The pop-up appears while I am working with different apps, routines, etc.

### Expected behavior

Not getting constant error messages.

### Which files are affected by this bug

(none)

### Operating system

macOS

### Which version of the operating system you are running.

14.8.4 (23J319)

### Package

Official Linux AppImage

### Nextcloud Server version

31.0.13 Enterprise

### Nextcloud Desktop Client version

Nextcloud Desktop Client Version 4.0.6 (macOS)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.16.1 to 3.16.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by i2h3**
Affects #9581.

### CODE REVIEW

File: shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.m [hunk 1]
```diff
@@ -52,6 +52,10 @@ -(void)process:(NSString*)line
     os_log_debug(_log, "Command: %{public}@", command);
     
     if([command isEqualToString:@"STATUS"]) {
+        if([split count] < 3) {
+            os_log_error(_log, "STATUS message too short: %{public}@", line);
+            return;
+        }
         NSString *result = [split objectAtIndex:1];
         NSArray *pathSplit = [split subarrayWithRange:NSMakeRange(2, [split count] - 2)]; // Get everything after location 2
         NSString *path = [pathSplit componentsJoinedByString:@":"];
```
Comment (nilsding) [inline shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.m:61]: We probably should join the paths in the other commands which deal with paths as well

would be fine by me to address that in a separate PR

**Review by nilsding — APPROVED** [review]

File: shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.m (hunk 1 above)
Comment (i2h3) [reply shell_integration/MacOSX/NextcloudIntegration/FinderSyncExt/FinderSyncSocketLineProcessor.m:61]: As clarified earlier today, I would not invest any work into the interprocess communication based on the UNIX sockets because those are replaced completely on `master` already.
